### ISSUE TITLE
Compatibility with UE4 Version 4.19.2

### ISSUE THREAD

**Issue by z3099644** [leapmotion/LeapUnreal#1]
I just tried this version of the plugin in my unreal project (running 4.19.2 of UE4) an when the project starts up, I get an error saying "Binaries for the 'LeapMotion' plugin are missing or incompatible with the current engine version'?

Edit: I am getting this with Version 4.18.3 also. Perhaps I am doing something wrong?

**Comment by getnamo** [comment]
Have you did you use the ```LeapMotion-v2.17.1-UE4.19.7z``` download from https://github.com/leapmotion/LeapUnreal/releases ?

**Comment by z3099644** [comment]
Oh oops, thanks, that's worked great!
