### ISSUE TITLE
My AR app get crashed as soon as it opens with leap motion plugin

### ISSUE THREAD

**Issue by hamu6259** [leapmotion/LeapUnreal#103]
Hi all:
     I am using the unreal engine version UE4.26 and related leap motion plugin version v3.7.11 for UE4.26. I have followed the instructions and copied the plugins in a separate folder and then when i open the project and dragged the "LeaphandsPawn" in the level and setting the auto "possess player" to 'player0' and then i choose to launch it on my android pixel 4 XL. the application gets deployed on android phone, but as soon as i open the app it gets crashed every single time and the log showing the error below. Kindly let me know anyone about this issue , i have to complete my study project as soon as possible. here is the error which the  log shows:
      
      "LogPlayLevel: Error:   11-26 12:31:14.739 19129 19162 D UE4     : [2021.11.26-11.31.14:739][  0]LogAndroid: Error: === Critical error: ===
LogPlayLevel: Error:   11-26 12:31:14.739 19129 19162 D UE4     : [2021.11.26-11.31.14:739][  0]LogAndroid: Error:
LogPlayLevel: Error:   11-26 12:31:14.739 19129 19162 D UE4     : [2021.11.26-11.31.14:739][  0]LogAndroid: Error: Fatal error: [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/CoreUObject/Private/Serialization/AsyncLoading.cpp] [Line: 3146]
LogPlayLevel: Error:   11-26 12:31:14.739 19129 19162 D UE4     : [2021.11.26-11.31.14:739][  0]LogAndroid: Error: Could not find SuperStruct BodyStateAnimInstance to create BSLowPolyRightAnimBP_C
LogPlayLevel: Error:   11-26 12:31:14.739 19129 19162 D UE4     : [2021.11.26-11.31.14:739][  0]LogAndroid: Error: [Callstack] 0x00000000B321B330 libUE4.so(0x000000000745A330)![Unknown]()  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000B321B0D0 libUE4.so(0x000000000745A0D0)!FAsyncPackage::EventDrivenSerializeExport(int)  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000B3214A78 libUE4.so(0x0000000007453A78)!FAsyncPackage::ProcessImportsAndExports_Event()  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000B3214310 libUE4.so(0x0000000007453310)!FAsyncPackage::Event_ProcessImportsAndExports()  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000B32215F0 libUE4.so(0x00000000074605F0)!FAsyncLoadingThread::ProcessAsyncLoading(int&, bool, bool, float, FFlushTree*)  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000B322AB54 libUE4.so(0x0000000007469B54)!FAsyncLoadingThread::TickAsyncThread(bool, bool, float, bool&, FFlushTree*)  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000B322A010 libUE4.so(0x0000000007469010)!FAsyncLoadingThread::TickAsyncLoading(bool, bool, float, FFlushTree*)  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000B323A384 libUE4.so(0x0000000007479384)!FAsyncLoadingThread::FlushLoading(int)  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000B3298368 libUE4.so(0x00000000074D7368)!FlushAsyncLoading(int)  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000B3577CA4 libUE4.so(0x00000000077B6CA4)!LoadPackageInternal(UPackage*, char16_t const*, unsigned int, FLinkerLoad*, FArchive*, FLinkerInstancingContext const*)  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000B35747E0 libUE4.so(0x00000000077B37E0)!LoadPackage(UPackage*, char16_t const*, unsigned int, FArchive*, FLinkerInstancingContext const*)  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000B7629A7C libUE4.so(0x000000000B868A7C)!UEngine::LoadMap(FWorldContext&, FURL, UPendingNetGame*, FString&)  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000B7625C5C libUE4.so(0x000000000B864C5C)!UEngine::Browse(FWorldContext&, FURL, FString&)  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000B6AF8350 libUE4.so(0x000000000AD37350)!UGameInstance::StartGameInstance()  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000B18F5BB0 libUE4.so(0x0000000005B34BB0)!FEngineLoop::Init()  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000B18F4728 libUE4.so(0x0000000005B33728)!AndroidMain(android_app*)  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000B1909C20 libUE4.so(0x0000000005B48C20)!android_main()  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000B193D0B8 libUE4.so(0x0000000005B7C0B8)![Unknown]()  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000E89C7AA0 libc.so(0x0000000000080AA0)![Unknown]()  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error: [Callstack] 0x00000000E8980DC6 libc.so(0x0000000000039DC6)![Unknown]()  []
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error:
LogPlayLevel: Error:   11-26 12:31:14.740 19129 19162 D UE4     : [2021.11.26-11.31.14:740][  0]LogAndroid: Error:
     
[The_Button.log](https://github.com/leapmotion/LeapUnreal/files/7608467/The_Button.log)

Alo please check the attached detailed log file from unreal engine.
 "

**Comment by Ultraleap-Dan** [comment]
Our hand tracking software does not currently support Android or mobile platforms so it will not be possible to include our hand tracking in your application for Android devices. 

I recommend keeping an eye on our social new feeds next year for any annoucements that we make about this. ;)
