### ISSUE TITLE
Leap tracking in hmd "floats"

### ISSUE THREAD

**Issue by JHanley85** [leapmotion/LeapUnreal#12]
When moving the hmd, and not moving the hands in space, the hands float in world space.

**Comment by getnamo** [comment]
You are likely not using Oculus or Vive and this means your target headset doesn't have the right timewarp timings set. If this is true, you'll want to adjust these using ```Set Leap Options``` https://github.com/leapmotion/leapunreal#global-functions with the struct data available here: https://github.com/leapmotion/LeapUnreal/blob/master/Source/LeapMotion/Public/LeapMotionData.h#L119. This can be called either in blueprint or in C++.

Specifically you'd want to adjust these 4 variables for your headset:

```
	/** Timewarp offset sampling in microseconds. The higher, the further back in time. */
	UPROPERTY(BlueprintReadWrite, Category = "Leap Options")
	float TimewarpOffset;

	/** Linear factor, useful for inverting timewarp effects for certain platforms (e.g. Oculus)*/
	UPROPERTY(BlueprintReadWrite, Category = "Leap Options")
	float TimewarpFactor;

	/** Number of frames we should predict forward (positive) or back (negative) from right now for hands */
	UPROPERTY(BlueprintReadWrite, Category = "Leap Options")
	float HandInterpFactor;

	/** Number of frames we should predict forward (positive) or back (negative) from right now for fingers */
	UPROPERTY(BlueprintReadWrite, Category = "Leap Options")
	float FingerInterpFactor;
```

Example vive normal values can be found here:
https://github.com/leapmotion/LeapUnreal/blob/master/Source/LeapMotion/Private/FLeapMotionInputDevice.cpp#L957

**Comment by JHanley85** [comment]
Oculus, also occurring in visualizer.

**Comment by getnamo** [comment]
If it also occurs in the visualizer it doesn't seem plugin related. Can you provide a video example of this behavior?

**Comment by FredRedPillVR** [comment]
Here is a google drive link containing three videos, one on our system (unreal engine 4), one on a unity game engine, and one last one on unity leap visualizer 

https://drive.google.com/drive/folders/17I5E9n03D_yx7D9_Hz9I17wIfcJzQGqU?usp=sharing

**Comment by getnamo** [comment]
@FredRedPillVR what version of the plugin is the UE4 video using?

**Comment by getnamo** [comment]
note to self: need to test oculus when it runs at 45fps vs 90fps. May need different timewarp settings under this environment.

**Comment by FredRedPillVR** [comment]
The UE4 video is running 4.0 of the Leap plugin

**Comment by FredRedPillVR** [comment]
well they all are on the same leap and pc, so they all are 4.0

**Comment by getnamo** [comment]
Not the leap SDK version, the version of the unreal plugin used in the ue4 video (4.0 isn't a valid answer)

**Comment by FredRedPillVR** [comment]
![leap](https://user-images.githubusercontent.com/42187679/50257054-56fb1880-03ae-11e9-85d5-50bafad1d742.PNG)

**Comment by getnamo** [comment]
Your plugin is out of date. Please check out https://github.com/leapmotion/LeapUnreal/releases and grab the latest plugin. Let me know if that changes the issue.

**Comment by z3099644** [comment]
I'm getting the same floatiness in ue4 too, but since my project is on
engine version 4.19.2, do you know if I am able to apply the latest plugin
(made for 4.21) to an older engine version? Or would it be possible to ask
for a fixed version compatible with 4.19.2?

**Comment by getnamo** [comment]
@z3099644  you should be able to take a newer build and recompile it in a C++ project to an older engine. Commonly there isn't a breaking change in API between engine versions for the leap plugin.

@FredRedPillVR how does the floatiness look like on e.g. https://github.com/leapmotion/LeapUnrealModules/blob/master/Content/Modules/Debug/TrackingTestbed.umap (example content) or a setup where you have 90fps? Also what on what hmd do you see this issue?

**Comment by z3099644** [comment]
Thanks for the tip Jan. When I tried to recompile it gave me this error:









*  While compiling
C:\LeapMotion419\HostProject\Intermediate\Build\BuildRules\HostProjectModuleRules.dll:
ERROR:
c:\LeapMotion419\HostProject\Plugins\LeapMotion\Source\LeapMotion\LeapMotion.Build.cs(25,43)
: error CS0103: The name 'EngineDirectory' does not exist in the current
context  ERROR:
c:\LeapMotion419\HostProject\Plugins\LeapMotion\Source\LeapMotion\LeapMotion.Build.cs(40,43)
: error CS0103: The name 'EngineDirectory' does not exist in the current
context  ERROR: Unable to compile source files.Took 0.6747575s to run
UnrealBuildTool.exe, ExitCode=5ERROR: Command failed (Result:5): D:\Program
Files\Epic Games\UE_4.19\Engine\Binaries\DotNET\UnrealBuildTool.exe
UE4Editor Win64 Development
-project="C:\LeapMotion419\HostProject\HostProject.uproject" -iwyu
-module=LeapMotion -module=LeapMotionEditor -module=BodyState
-receipt=C:\LeapMotion419\HostProject\Plugins\LeapMotion\Binaries\Win64\UE4Editor.target
-NoHotReload. See logfile for details:
'UnrealBuildTool-2018.12.23-14.56.46.txt'       (see D:\Program Files\Epic
Games\UE_4.19\Engine\Programs\AutomationTool\Saved\Logs\UAT_Log.txt for
full exception trace)AutomationTool exiting with ExitCode=5 (5)BUILD FAILED*


Any ideas?

**Comment by getnamo** [comment]
@z3099644 
add the following lines in your LeapMotion.build.cs (https://github.com/leapmotion/LeapUnreal/blob/master/Source/LeapMotion/LeapMotion.Build.cs):
```c#
		private string EngineDirectory
		{
			get { return Path.GetFullPath("../"); }
		}
```

this code block should go below this place

```c#
		private string ModulePath
		{
			get { return ModuleDirectory; }
		}

		//paste here
```
The rest of the plugin should compile as is :)

**Comment by getnamo** [comment]
@JHanley85 Very thorough report, thanks!
Just to confirm I'm getting the setup correctly, this is using an Oculus with a Rigel unit? It looks like I need to adjust some of the timewarp settings for that combination if that is so (the float amount doesn't seem excessive though). 

Note that you can also adjust these settings yourself directly in blueprint by calling ```SetLeapOptions``` with tracking fidelity set to custom and adjusting the values for _TimewarpOffset_, _TimewarpFactor_, _HandInterpFactor_, and _FingerInterpFactor_, You'll find the current defaults at: https://github.com/leapmotion/LeapUnreal/blob/master/Source/LeapMotion/Private/FLeapMotionInputDevice.cpp#L1022. See https://github.com/leapmotion/LeapUnreal#set-leap-options for details. If you find a good set of values before I get to it, let me know.

**Comment by z3099644** [comment]
> 
> 
> @z3099644
> add the following lines in your LeapMotion.build.cs (https://github.com/leapmotion/LeapUnreal/blob/master/Source/LeapMotion/LeapMotion.Build.cs):
> 
> ```cs
> 		private string EngineDirectory
> 		{
> 			get { return Path.GetFullPath("../"); }
> 		}
> ```
> 
> this code block should go below this place
> 
> ```cs
> 		private string ModulePath
> 		{
> 			get { return ModuleDirectory; }
> 		}
> 
> 		//paste here
> ```
> 
> The rest of the plugin should compile as is :)

@getnamo, your fix above worked great on that version (thanks!!), but today when I tried it with your latest release (3.3.0) to recompile it to work with UE 4.19.2 it gave me a compile error. Any ideas on what I am doing wrong? =)

**Comment by getnamo** [comment]
@z3099644 open an new issue with compile log errors, but there may be changes in 4.22 that are not 4.19 compatible.

**Comment by getnamo** [comment]
closed due to merged fix
