### ISSUE TITLE
ANY_PACKAGE deprecated macro

### ISSUE THREAD

**Issue by FriMeDev** [leapmotion/LeapUnreal#125]
**File**: \Source\ThirdParty\BodyState\Private\BodyStateUtility.h (Line 40)

The macro `ANY_PACKAGE` is deprecated and will not be supported in future UE-Versions.

```
#define ANY_PACKAGE UE_DEPRECATED_MACRO(5.1, "ANY_PACKAGE has been deprecated. Either use full path name of objects (including classes) or provide a valid Outer for *FindObject* functions") ((UPackage*)-1)
```
**Source**: ...\UE_5.1\Engine\Source\Runtime\CoreUObject\Public\UObject\ObjectMacros.h (Line 663)

**Comment by Ultraleap-Dan** [comment]
This is now in our latest Unreal release 5.10, please can you update to this version, retest and let us know if this is resolved?

**Comment by Fritte795** [comment]
Thank you @Ultraleap-Dan. I will retest it as soon as possible. I will post my feedback here again.
