### ISSUE TITLE
It´s not working at all, the example project says "Leap Not Loaded", Plugin is enabled

### ISSUE THREAD

**Issue by juangea** [leapmotion/LeapUnreal#13]
Hi there, specially you @getnamo , thanks for this.

I´m trying the new plugin with my own project and with the Modules project, and no matter what I do, the starting map of the modules project says "Leap Not Loaded".

I tried turning off and on again the plugin, but it does not work, I don´t get any kind of tracking at all.

PLease help I should have a demo on this by tomorrow and I though it should work without a problem but I´m lost here!

**Comment by juangea** [comment]
Ok, solved, somehow I had the SDK 3 instead of the SDK 4... you should name this in the readme because for some reason the LeapMotion website lead me to download the 3.2 in the first place, I don´t know why :)

**Comment by getnamo** [comment]
I believe that part was mentioned in setup, but I'll add it to the readme as a troubleshooting step.
