### ISSUE TITLE
Deformed low poly hand in Packaged Builds

### ISSUE THREAD

**Issue by getnamo** [leapmotion/LeapUnreal#14]
Reference https://forums.leapmotion.com/t/deformed-hand-after-packaging-unreal-engine-project/7329

Note to self: Appears recent changes in rigging have broken something in packaged builds

**Comment by JG-LY** [comment]
@getnamo Do you have any idea when the issue will be addressed? Is there a feasible workaround (e.g., downgrade the plugin version or Unreal Engine version)?

**Comment by getnamo** [comment]
I'm looking to address this in about a week. In meantime you can try earlier releases here: https://github.com/leapmotion/LeapUnreal/releases to see if they do not have the issue.

**Comment by JG-LY** [comment]
Did you already get a chance to address this issue?

**Comment by getnamo** [comment]
https://github.com/leapmotion/LeapUnreal/releases/tag/v2.17.1 works as expected but you need to use Unreal Engine 4.19.

Currently looking into the issue, should be addressed shortly.

**Comment by getnamo** [comment]
note to self: 
- After replication of old v2.17 plugin in 4.20 it appears it's an engine api change or bug. Will need to find a work around. Might be related: https://answers.unrealengine.com/questions/811400/a-simple-animgraphnode-class-extended-from-animgra.html
- Appears to be causing an additional rotation that tracks hmd to hands, but only in packaged mode.

**Comment by michela** [comment]
Jan are you on UDN? If not, let me know if you need help getting Epic input on this.

**Comment by juangea** [comment]
Waiting for this to be solved too, I´ll write here instead of writing in my closed issue, since it´s the same problem and this way I can save you having to look in the other issue @getnamo 

I hope you find the solution soon :S

**Comment by juangea** [comment]
How is this going? 

Any progress?

Thanks.

**Comment by getnamo** [comment]
This issue has the high priority, still looking for a workaround. Will update when there's progress.

**Comment by juangea** [comment]
Thanks, this is driving me crazy, I don´t know how am I going to make a release if this is not solved :P

**Comment by getnamo** [comment]
Fixed in https://github.com/leapmotion/LeapUnreal/commit/4878118568df461a37fd7d75170fdabf435d32f6 available as a release at https://github.com/leapmotion/LeapUnreal/releases/tag/v3.0.1

**Comment by acttogreen** [comment]
thanks
