### ISSUE TITLE
Unreal Engine crashes randomly in editor

### ISSUE THREAD

**Issue by nofyt** [leapmotion/LeapUnreal#15]
Unreal Engine crashes when leap motion is connected. This can happen when editing a blueprint, when PIE etc, but it seems to happen more frequently when opening a blueprint. No difference if running from visual studio or not. Help is appreciated!
![capture](https://user-images.githubusercontent.com/8833731/45152974-d3d4fe80-b1d2-11e8-9f9f-7d3eaa72eca2.PNG)

Assertion failed: !Pose[ParentIndex].ContainsNaN() [File:c:\program files\epic games\ue_4.20\engine\source\runtime\engine\public\BonePose.h] [Line: 604]

KERNELBASE
UE4Editor_ApplicationCore
UE4Editor_Core
UE4Editor_Core
UE4Editor_BodyState!FCSPose<FCompactPose>::CalculateComponentSpaceTransform() [c:\program files\epic games\ue_4.20\engine\source\runtime\engine\public\bonepose.h:606]
UE4Editor_BodyState!FCSPose<FCompactPose>::CalculateComponentSpaceTransform() [c:\program files\epic games\ue_4.20\engine\source\runtime\engine\public\bonepose.h:597]
UE4Editor_BodyState!FCSPose<FCompactPose>::GetComponentSpaceTransform() [c:\program files\epic games\ue_4.20\engine\source\runtime\engine\public\bonepose.h:568]
UE4Editor_BodyState!FAnimNode_ModifyBodyStateMappedBones::EvaluateSkeletalControl_AnyThread() [c:\p4\llidmr_rd0050479_sim-shared_7925\ue4\simcore\plugins\leapmotion\source\bodystate\private\animnode_modifybodystatemappedbones.cpp:46]
UE4Editor_AnimGraphRuntime
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
UE4Editor_Core
kernel32
ntdll

**Comment by getnamo** [comment]
Seems related to https://github.com/leapmotion/LeapUnreal/issues/4, the fix should have been included in v3.0 of the plugin can you confirm you're using the v3.0 release?

**Comment by elliotstronge** [comment]
Having the same issue. Throws the same exception in a fresh project with Leap v4.0, plugin v3.2, on Unreal 4.21.2. 

In terms of usability it seems to switch randomly between tracking really well, and the next time running it tracks horribly and the hands keep flipping and the fingers get all screwed up and janky.

**Comment by getnamo** [comment]
This may suggest there is still something unsafe about how the data is handled, but only seems to be apparent on some CPU architectures/OSs. Try a temporary workaround by disabling multi-thread animation updates in your ```BSLowPolyLeftAnimBP``` and ```BSLowPolyRightAnimBP``` as shown here

![image](https://user-images.githubusercontent.com/542365/51582259-2b24f400-1e80-11e9-91c0-a3fa3dc4da7b.png)

**Comment by elliotstronge** [comment]
No change unfortunately. Works perfectly the first time after running from Visual Studio, but then the next times either crash in BonePose.h - Line 583 `check(!Pose[BoneIndex].ContainsNaN());` or the hands are messed up and almost completely inverted at times.

**Comment by getnamo** [comment]
I was able to replicate a crash of this type while fixing issue 12, grab this release https://github.com/leapmotion/LeapUnreal/releases/tag/v3.2.1 and let me know if the issue has disappeared.

**Comment by elliotstronge** [comment]
Awesome thank you, I'll give it a go today.

**Comment by getnamo** [comment]
Note to self: need to confirm all instances of this issue has been addressed.

**Comment by getnamo** [comment]
Note to self: Replicated crash condition.

```
Assertion failed: !Pose[ParentIndex].ContainsNaN() [File:c:\program files\epic games\ue_4.21\engine\source\runtime\engine\public\BonePose.h] [Line: 584]

UE4Editor_Core!FDebug::AssertFailed() [d:\build\++ue4\sync\engine\source\runtime\core\private\misc\assertionmacros.cpp:417]
UE4Editor_BodyState!FCSPose<FCompactPose>::CalculateComponentSpaceTransform() [c:\program files\epic games\ue_4.21\engine\source\runtime\engine\public\bonepose.h:586]
UE4Editor_BodyState!FCSPose<FCompactPose>::CalculateComponentSpaceTransform() [c:\program files\epic games\ue_4.21\engine\source\runtime\engine\public\bonepose.h:581]
UE4Editor_BodyState!FCSPose<FCompactPose>::GetComponentSpaceTransform() [c:\program files\epic games\ue_4.21\engine\source\runtime\engine\public\bonepose.h:548]
UE4Editor_BodyState!FAnimNode_ModifyBodyStateMappedBones::EvaluateSkeletalControl_AnyThread() [c:\users\admin\documents\github\leapcompilealt\plugins\leapmotion\source\bodystate\private\animnode_modifybodystatemappedbones.cpp:46]
UE4Editor_AnimGraphRuntime!FAnimNode_SkeletalControlBase::EvaluateComponentSpace_AnyThread() [d:\build\++ue4\sync\engine\source\runtime\animgraphruntime\private\bonecontrollers\animnode_skeletalcontrolbase.cpp:155]
UE4Editor_Engine!FComponentSpacePoseLink::EvaluateComponentSpace() [d:\build\++ue4\sync\engine\source\runtime\engine\private\animation\animnodebase.cpp:352]
UE4Editor_Engine!FAnimNode_ConvertComponentToLocalSpace::Evaluate_AnyThread() [d:\build\++ue4\sync\engine\source\runtime\engine\private\animation\animnodespaceconversions.cpp:34]
UE4Editor_Engine!FPoseLink::Evaluate() [d:\build\++ue4\sync\engine\source\runtime\engine\private\animation\animnodebase.cpp:290]
UE4Editor_Engine!FAnimInstanceProxy::EvaluateAnimationNode() [d:\build\++ue4\sync\engine\source\runtime\engine\private\animation\animinstanceproxy.cpp:1155]
UE4Editor_Engine!FAnimInstanceProxy::EvaluateAnimation() [d:\build\++ue4\sync\engine\source\runtime\engine\private\animation\animinstanceproxy.cpp:1132]
UE4Editor_Engine!UAnimInstance::ParallelEvaluateAnimation() [d:\build\++ue4\sync\engine\source\runtime\engine\private\animation\animinstance.cpp:618]
UE4Editor_Engine!USkeletalMeshComponent::EvaluateAnimation() [d:\build\++ue4\sync\engine\source\runtime\engine\private\components\skeletalmeshcomponent.cpp:1707]
UE4Editor_Engine!USkeletalMeshComponent::PerformAnimationProcessing() [d:\build\++ue4\sync\engine\source\runtime\engine\private\components\skeletalmeshcomponent.cpp:1789]
UE4Editor_Engine!USkeletalMeshComponent::PerformAnimationEvaluation() [d:\build\++ue4\sync\engine\source\runtime\engine\private\components\skeletalmeshcomponent.cpp:1757]
UE4Editor_Engine!USkeletalMeshComponent::RefreshBoneTransforms() [d:\build\++ue4\sync\engine\source\runtime\engine\private\components\skeletalmeshcomponent.cpp:2080]
UE4Editor_UnrealEd!UDebugSkelMeshComponent::RefreshBoneTransforms() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\animation\debugskelmeshcomponent.cpp:479]
UE4Editor_Engine!USkinnedMeshComponent::TickComponent() [d:\build\++ue4\sync\engine\source\runtime\engine\private\components\skinnedmeshcomponent.cpp:778]
UE4Editor_Engine!USkeletalMeshComponent::TickComponent() [d:\build\++ue4\sync\engine\source\runtime\engine\private\components\skeletalmeshcomponent.cpp:1239]
UE4Editor_UnrealEd!UDebugSkelMeshComponent::TickComponent() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\animation\debugskelmeshcomponent.cpp:788]
UE4Editor_Engine!FActorComponentTickFunction::ExecuteTickHelper<<lambda_3709318d6805ded621dc256d05754a1f> >() [d:\build\++ue4\sync\engine\source\runtime\engine\classes\gameframework\actor.h:3143]
UE4Editor_Engine!FActorComponentTickFunction::ExecuteTick() [d:\build\++ue4\sync\engine\source\runtime\engine\private\components\actorcomponent.cpp:800]
UE4Editor_Engine!TGraphTask<FTickFunctionTask>::ExecuteTask() [d:\build\++ue4\sync\engine\source\runtime\core\public\async\taskgraphinterfaces.h:829]
UE4Editor_Core!FNamedTaskThread::ProcessTasksNamedThread() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:679]
UE4Editor_Core!FNamedTaskThread::ProcessTasksUntilQuit() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:575]
UE4Editor_Core!FTaskGraphImplementation::WaitUntilTasksComplete() [d:\build\++ue4\sync\engine\source\runtime\core\private\async\taskgraph.cpp:1444]
UE4Editor_Engine!FTickTaskSequencer::ReleaseTickGroup() [d:\build\++ue4\sync\engine\source\runtime\engine\private\ticktaskmanager.cpp:556]
UE4Editor_Engine!FTickTaskManager::RunTickGroup() [d:\build\++ue4\sync\engine\source\runtime\engine\private\ticktaskmanager.cpp:1474]
UE4Editor_Engine!UWorld::RunTickGroup() [d:\build\++ue4\sync\engine\source\runtime\engine\private\leveltick.cpp:783]
UE4Editor_Engine!UWorld::Tick() [d:\build\++ue4\sync\engine\source\runtime\engine\private\leveltick.cpp:1468]
UE4Editor_Persona!FAnimationEditorPreviewScene::Tick() [d:\build\++ue4\sync\engine\source\editor\persona\private\animationeditorpreviewscene.cpp:1106]
UE4Editor_UnrealEd!FTickableEditorObject::TickObjects() [d:\build\++ue4\sync\engine\source\editor\unrealed\public\tickableeditorobject.h:45]
UE4Editor_UnrealEd!UEditorEngine::Tick() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\editorengine.cpp:1517]
UE4Editor_UnrealEd!UUnrealEdEngine::Tick() [d:\build\++ue4\sync\engine\source\editor\unrealed\private\unrealedengine.cpp:403]
UE4Editor!FEngineLoop::Tick() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launchengineloop.cpp:3699]
UE4Editor!GuardedMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\launch.cpp:174]
UE4Editor!GuardedMainWrapper() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:145]
UE4Editor!WinMain() [d:\build\++ue4\sync\engine\source\runtime\launch\private\windows\launchwindows.cpp:276]
UE4Editor!__scrt_common_main_seh() [f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:283]
kernel32
ntdll
```

points to https://github.com/leapmotion/LeapUnreal/blob/master/Source/BodyState/Private/AnimNode_ModifyBodyStateMappedBones.cpp#L46

which is likely a race condition causing NaN despite a scope lock. Will need to isolate producer/consumer threads more thoroughly.

**Comment by yuhe00** [comment]
Hey, we're using this plugin in production and can confirm that it does not only crash in the editor, but in packaged build as well, with the same crash log 🙁

**Comment by AlexGorcea** [comment]
Can confirm this with UE 4.22.1
Constant crashes.

**Comment by getnamo** [comment]
@AlexGorcea out of curiosity, have you tried disabling multi-threading inside your anim blueprints and see if that reduces crash occurence?

**Comment by AlexGorcea** [comment]
@getnamo it's disabled, but it doesn't change anything.

**Comment by getnamo** [comment]
Ok after some testing I suspect it's the estimator not having a scope lock. Repull master (to get this fix: https://github.com/leapmotion/LeapUnreal/commit/9944876e69799338388d6c0505458ee931c54be0) and compile and let me know if that fixed the issue.

**Comment by getnamo** [comment]
Added release for testing: https://github.com/leapmotion/LeapUnreal/releases/tag/v3.3.4

**Comment by AlexGorcea** [comment]
It looks good now, so far no crashes, but will keep you posted.

**Comment by AlexGorcea** [comment]
@getnamo Quick question relating to this. It seems to me like the crashes are related to the bones for the fingers. Is there any way to disable the hands altogether and just get the position of the hands themselves?

**Comment by getnamo** [comment]
@AlexGorcea I believe I know what's happening. When accessing get bone for enum outside of the ModifyMappedBones and BodyStateEstimators (from latest build) those accesses are not thread safe. What needs to be done is to create a new skeleton instance based on the thread you're in, I'll need to modify a few things for that to get fixed. In meantime if you can access your data from the [BS estimator update callback](https://github.com/leapmotion/LeapUnreal/blob/master/Source/BodyState/Public/BodyStateEstimatorComponent.h#L23) your access and updates will be threadsafe. Cache any data you wish to update separately in e.g. anim thread.
