### ISSUE TITLE
Reparent AnimInstance causes editor to crash

### ISSUE THREAD

**Issue by Phil-Littler** [leapmotion/LeapUnreal#17]
When trying to re-parent my own AnimInstance as BodyStateAnimInstance as per the Custom Rigging Instructions, my editor crashes with the following error:

Assertion failed: (Index >= 0) & (Index < ArrayNum) [File:C:\Program Files\Epic Games\UE_4.20\Engine\Source\Runtime\Core\Public\Containers/Array.h] [Line: 611] Array index out of bounds: -2 from an array of size 67

I am using a rigged human model from: https://secure.axyz-design.com/

As a reference, the skeleton structure is as follows:
![image](https://user-images.githubusercontent.com/5123307/45425958-b8666980-b692-11e8-8603-7db3c70e3e04.png)
 
Regards,
Phil

**Comment by getnamo** [comment]
I suspect this related to the auto-rigging that happens at the startup of [```BodyStateAnimInstance#L124```](https://github.com/leapmotion/LeapUnreal/blob/master/Source/BodyState/Private/BodyStateAnimInstance.cpp#L124)

Do you have the logs related to the crash saved under ```Saved/Logs```? it may point to the part that doesn't behave right

**Comment by Phil-Littler** [comment]
Please see attached log:
[LeapModules-backup-2018.09.12-13.34.38.log](https://github.com/leapmotion/LeapUnreal/files/2377947/LeapModules-backup-2018.09.12-13.34.38.log)

**Comment by BaazarProductions** [comment]
Any progress with this? This is happening for me as well.

**Comment by getnamo** [comment]
Can you show the skeleton hierarchy for the anim instance you are reparenting? 

I'll carve out some time to fix this. Any logs you can provide will also be helpful.

**Comment by BaazarProductions** [comment]
Thank you! Attached are screenshots of the rig and the log.
Let me know if you need any further information.

[UE4CC-Windows-5EE42A654DCFBF2A2DEBD08E8EF68EBC_0000.zip](https://github.com/leapmotion/LeapUnreal/files/2985763/UE4CC-Windows-5EE42A654DCFBF2A2DEBD08E8EF68EBC_0000.zip)
![Capture](https://user-images.githubusercontent.com/47745483/54645934-cc808e80-4a5a-11e9-96bb-a63366ab335e.PNG)
![Capture2](https://user-images.githubusercontent.com/47745483/54645935-cd192500-4a5a-11e9-9311-b8de4a5e26b9.PNG)
![Capture3](https://user-images.githubusercontent.com/47745483/54645937-cd192500-4a5a-11e9-9267-cfd26b020f57.PNG)
![Capture4](https://user-images.githubusercontent.com/47745483/54645938-cd192500-4a5a-11e9-8d00-fe509a6415f3.PNG)
![Capture5](https://user-images.githubusercontent.com/47745483/54645939-cd192500-4a5a-11e9-8b94-87c813f34042.PNG)

**Comment by BaazarProductions** [comment]
> Can you show the skeleton hierarchy for the anim instance you are reparenting?
> 
> I'll carve out some time to fix this. Any logs you can provide will also be helpful.

When would be good to check back in with you about a possible solution?

Thanks again for the assistance!

**Comment by getnamo** [comment]
I'm currently away from my workstation this week due to an event, I'll be able to look into this next week.

If your rigging can't wait that long, please try the Direct Rigging path (see these assets for examples https://github.com/leapmotion/LeapUnreal/tree/master/Content/DirectRigging/LowPoly) which does not depend on automapping or the bodystate anim instance.

**Comment by BaazarProductions** [comment]
> I'm currently away from my workstation this week due to an event, I'll be able to look into this next week.
> 
> If your rigging can't wait that long, please try the Direct Rigging path (see these assets for examples https://github.com/leapmotion/LeapUnreal/tree/master/Content/DirectRigging/LowPoly) which does not depend on automapping or the bodystate anim instance.

Thank you - my apologies, I did not know there was a direct rigging method. I'll do my best with that until you have time next week! :)

**Comment by BaazarProductions** [comment]
> I'm currently away from my workstation this week due to an event, I'll be able to look into this next week.
> 
> If your rigging can't wait that long, please try the Direct Rigging path (see these assets for examples https://github.com/leapmotion/LeapUnreal/tree/master/Content/DirectRigging/LowPoly) which does not depend on automapping or the bodystate anim instance.

Ok - I'm almost there. My character is rigged in the blueprint with 0 errors but I just can't get the leap motion to animate. In the autorig examples, the arms and hands animate directly in the blueprint preview window, but in the direct rig, it's always static unless added to another blueprint. What am I missing here?

**Comment by getnamo** [comment]
That's helpful, I'll take a look. Any possibility of sharing just the skeleton (no mesh needed, just bone list in .uasset) for replication tests?

Note to self: appears to have multiple many-bone children which may target the hand root incorrectly. Should default auto-map to false to stop it from crashing on init.

**Comment by BaazarProductions** [comment]
> That's helpful, I'll take a look. Any possibility of sharing just the skeleton (no mesh needed, just bone list in .uasset) for replication tests?
> 
> Note to self: appears to have multiple many-bone children which may target the hand root incorrectly. Should default auto-map to false to stop it from crashing on init.

Thank you Jan. I'll PM you.

**Comment by BaazarProductions** [comment]
> That's helpful, I'll take a look. Any possibility of sharing just the skeleton (no mesh needed, just bone list in .uasset) for replication tests?
> 
> Note to self: appears to have multiple many-bone children which may target the hand root incorrectly. Should default auto-map to false to stop it from crashing on init.

Skeleton Uasset is here:
https://drive.google.com/open?id=1xVv5JPnpYiQzU1ZRkuF-l6ZtYEd1D8Z2
