### ISSUE TITLE
Build Preview, hand mesh deformed

### ISSUE THREAD

**Issue by acttogreen** [leapmotion/LeapUnreal#18]
it run smoothly on editor but when i package it the hand mesh deformed and sometime glitchy
Plugin 3.0 with latest Modules
UE 4 20.2
![leap bug](https://user-images.githubusercontent.com/12003515/45477255-54fc3a80-b76b-11e8-96a9-187e78dc1dfc.gif)

**Comment by getnamo** [comment]
Duplicate of https://github.com/leapmotion/LeapUnreal/issues/14, will be addressing this shortly.

**Comment by getnamo** [comment]
fixed in https://github.com/leapmotion/LeapUnreal/releases/tag/v3.0.1
