### ISSUE TITLE
If leap is not connected unreal process does not stop 

### ISSUE THREAD

**Issue by baloo887** [leapmotion/LeapUnreal#24]
Hi guys,
I have a strange behaviour in one of my unreal projects, using this plugin.

The problem is: after the end of the execution, if the leap motion is unplugged (and wasn't plugged before), a "U4game.exe" process is kept alive. This process uses 100~400 MB of memory, and one of these task is added at each execution.

This happens only with a packaged project, on windows 10.

Reading the logs and looking at the plugin code, it seems that the shutdown routine of the project is stopped by the "FLeapWrapper::CloseConnection()" method in the LeapWrapper.cpp class.

Can you please check on this issue or advice on how to manage a project that could not have the leap motion device always connected.

P.S.: here's the last rows of my log file:
`[2018.11.06-17.42.39:990][446]LogModuleManager: Shutting down and abandoning module LeapMotion (118)
[2018.11.06-17.42.39:990][446]LeapMotionLog: Leap Plugin shutdown.
[2018.11.06-17.42.39:990][446]BodyStateLog: Id: 1
[2018.11.06-17.42.39:990][446]LogUObjectArray: Warning: Empty slot
[2018.11.06-17.42.39:990][446]BodyStateLog: BodyState::Device Detached: Leap Motion (1)`

Thanks

**Comment by getnamo** [comment]
This sounds like a bug, will try to get a replication. Likely https://github.com/leapmotion/LeapUnreal/blob/master/Source/LeapMotion/Private/LeapWrapper.cpp#L84 which if a device is never found, may never quit, but it should. I suspect https://github.com/leapmotion/LeapUnreal/blob/master/Source/LeapMotion/Private/LeapWrapper.cpp#L467 loop.

**Comment by baloo887** [comment]
Thanks for the hints @getnamo, let me know if you're able to reproduce it.

**Comment by getnamo** [comment]
note to self: appears ```LeapPollConnection``` never times out in v4

**Comment by getnamo** [comment]
should be fixed in https://github.com/leapmotion/LeapUnreal/commit/e8a536d3d1adebfd11feb5f036911a3bd58fd3ec, repull master for fix.

Fix is a workaround with a timeout of 3 seconds using waitFor instead of open ended wait.

**Comment by baloo887** [comment]
I've tested it today and it's working! Thanks for the fix!

**Comment by getnamo** [comment]
Latest release supports fix.
