### ISSUE TITLE
Leap events are not getting called( Solved )

### ISSUE THREAD

**Issue by mohs1n** [leapmotion/LeapUnreal#25]
I can't call the Hand grab or pinch events using the v2.17.1 in UE4.19. My Leap software is v4 too. 
Please any help would be appreciated.

**Comment by getnamo** [comment]
Does general tracking work? How about the Leap Motion Visualizer?

**Comment by mohs1n** [comment]
General tracking works, I don't know about visualiser. I've done this in the past using your tutorial for grabbing stuff and it worked perfectly in ue 4.13 but the exact same thing now is not working in 4.19, what could be the problem? Like I tried printing basic print with grab and that isn't triggering too

**Comment by mohs1n** [comment]
Thank you for getting back, basically it didn't start event until I click into the viewport while it's being played in non VR mode maybe a bug or something. Anyways it's solved now so please close this :)
