### ISSUE TITLE
Two pairs of hands in Desktop mode

### ISSUE THREAD

**Issue by michela** [leapmotion/LeapUnreal#26]
When using LeapDesktopActor with LeadHandsPawn as per the documentation,  I get two sets of hands in 4.21 - orientated for VR and for desktop. 

![crazy-hands](https://user-images.githubusercontent.com/99073/48823122-c8e24100-edb3-11e8-88cf-305397065e68.gif)

**Comment by getnamo** [comment]
You should use either the *LeapDesktopActor* for **desktop** mode or the *LeapHandsPawn* for **vr mode**, preferably not both at the same time or you'll get that awesome gif above. The main difference between the assets is that the LeapDesktop actor will change tracking mode to be optimized for desktop use, you can see this if you open the blueprint graphs to see what gets called on begin play.

I've clarified the readme to signify it's _either or_ https://github.com/leapmotion/LeapUnreal#how-to-use-it---convenience-rigged-pawn.
