### ISSUE TITLE
No hands visible with WMR

### ISSUE THREAD

**Issue by caddi91** [leapmotion/LeapUnreal#3]
I'm working with the Acer WMR headset. Following the quick start instructions I can't get the new plugin to show me the hands in the LeapHandsPawn. With an older version of the plugin an the FloatingHandsCharacter I placed the Pawn in the scene and the hands were instantly shown.

In the new version I tried to set the tracking origin on eye level unfortunately without success. Furthermore I reviewed the blueprints and printed the visibility booleans in BSLowPolyHand, they were false every time - not sure wether these flags were the right hints. 
At start, in console appears correctly " Adjusting Origin for SteamVR", since the WMR headset connects to unreal through steam vr.

Via the Leap Motion Visualizer the hands are tracked correctly and as I said in my old application with plugin version 2.0.0 there are hands too. 

Hope you have any ideas how to get these hands in my application, or what i'm doing wrong ;)
Thanks!

**Comment by getnamo** [comment]
Have you installed the latest leap installer? it's now at v4.0 see https://developer.leapmotion.com/get-started or https://warehouse.leapmotion.com/apps/4621/download for direct link.

**Comment by getnamo** [comment]
You can confim the version in the control panel -> about under software version

**Comment by caddi91** [comment]
Oh I had but it seems it was a little bit buggy...  After a new installation of the SDK it's working and the hands are visible. Looking forward to do great things with the plugin! Thank you!

**Comment by getnamo** [comment]
Excellent, I'll need to make sure this mismatch is made more clear to the user. I'll add this as a fix issue.

**Comment by getnamo** [comment]
LeapC api cannot get service version, documentation already mentions v4 install step. Closing as there is nothing else to do on this issue at this time.
