### ISSUE TITLE
Create new Leap Component Events

### ISSUE THREAD

**Issue by Teotavares** [leapmotion/LeapUnreal#30]
how create a pinched blueprint exemple, using print string or another function? thank you.

**Comment by getnamo** [comment]
Either you use input mapping with Leap (L/R) Pinch events 
https://github.com/leapmotion/LeapUnreal#grab-and-pinch

or you add a leap component
https://github.com/leapmotion/LeapUnreal#leap-component-events

and click 'On Hand Pinched' + button to receive the event.

**Comment by Teotavares** [comment]
thank you!

Em qui, 13 de dez de 2018 às 09:22, Jan Kaniewski <notifications@github.com>
escreveu:
