### ISSUE TITLE
Add support for multi-device

### ISSUE THREAD

**Issue by getnamo** [leapmotion/LeapUnreal#31]
see http://blog.leapmotion.com/multiple-devices/

Todo:
- [x] Scaffold
- [x] Working build
- [x] Stable release
- [x] Documentation

**Comment by myronho2006** [comment]
Will there be any or plan about the update of adding support for multi-device in ue4?

**Comment by getnamo** [comment]
Waiting on an updated dll, but it should be in theory fairly straightforward to get basic support working after that. No specific timeline however, depends on how popular this feature request is.

**Comment by FredRedPillVR** [comment]
I would LOVE to have this feature, it would be a huge benefit because in our use case that I use Leap in, sometimes the hand can get lost but having a device above and one mounted on a HMD would greatly help.

**Comment by getnamo** [comment]
Feature will be tracked in this branch: https://github.com/leapmotion/LeapUnreal/tree/feat-multi-device

**Comment by getnamo** [comment]
The https://github.com/leapmotion/LeapUnreal/tree/feat-multi-device branch is now in working state if you're brave enough to try. Documentation and a few stability fixes outstanding.

**Comment by getnamo** [comment]
Stable release and documentation available at https://github.com/leapmotion/LeapUnreal/tree/feat-multi-device#multi-device-branch

**Comment by getnamo** [comment]
Binary release: https://github.com/leapmotion/LeapUnreal/releases/tag/v3.4.0

**Comment by getnamo** [comment]
added links about MD in base readme, closing issue.
