### ISSUE TITLE
Make custom rigging example video

### ISSUE THREAD

**Issue by getnamo** [leapmotion/LeapUnreal#35]
A step by step process is helpful for some.

**Comment by cianarogers** [comment]
Hi, I followed your suggestions to use the direct rigging and its working mostly but now my hand looks like this
![handdistort](https://user-images.githubusercontent.com/27292050/52300276-7564a580-2955-11e9-8289-d2efc6100ac4.PNG)

I then tried using the ue4 mannequin and it works fine just the rotation offset needs to be modified
![mannopen](https://user-images.githubusercontent.com/27292050/52300337-9927eb80-2955-11e9-8dd1-191990e6f7b5.PNG)


with the mannequin the hand closes but with the other hand the fingers won't move and are stuck together 
![mannclose](https://user-images.githubusercontent.com/27292050/52300384-b6f55080-2955-11e9-841b-68c168d6841e.PNG)

i think this means i'm doing the direct rigging correctly but I think the other hand is missing something that the mannequin hand has just not sure what I'm missing

are there any specific requirements for the hand to work properly like physics needed or bone placement?

**Comment by cianarogers** [comment]
You were right, the rotation was just off. My preadjustment needed to be -90 on x and 90 on y for them to work properly. 
![handswork](https://user-images.githubusercontent.com/27292050/52302990-cb891700-295c-11e9-8fc3-b083988a4386.png)

Thank you so much for the help, I really appreciated it I've spent like 3 or 4 days trying to get these hands to work lol I'm also still newish to Unreal and don't really know anything about rigging hands. Hopefully this will help future people having trouble :)
