### ISSUE TITLE
UE4 4.20 Module adding does not work

### ISSUE THREAD

**Issue by lumbbumba** [leapmotion/LeapUnreal#38]
Hi, 

I was trying to using the Leap Motion API in code and followed these[ instructions](https://developer-archive.leapmotion.com/documentation/v2/unreal/unreal/Leap_Unreal_Cpp_Tutorial.html)

I could not add the modules "LeapMotionController" and "Leap".

> Could not find definition for module 'LeapMotionController' (referenced via Target -> OpenCVLinking.Build.cs)

But when I use the module "LeapMotion" it builds fine but I can not include header files from leapMotion.

Is this an outdated documentation or am I doing something wrong?
And can we get any example how to use C++ with this plugin? Maybe in an Actor Class`?
Sry for bad english.

Thanks.
  SOLVED:

You just need to add "MotionLeap" to the modules.

**Comment by getnamo** [comment]
Yes those are old instructions. The one found on this github readme are the most up to date.
