### ISSUE TITLE
Correct for Reversed Hands

### ISSUE THREAD

**Issue by BaazarProductions** [leapmotion/LeapUnreal#40]
Is there a fast work around to use some of the VR examples in desktop mode? All of the hands are reversed when simply running in the editor window.

**Comment by getnamo** [comment]
Use SetLeapMode (https://github.com/leapmotion/LeapUnreal#set-leap-mode) to change optimization and orientation to desktop tracking in e.g. begin play

**Comment by BaazarProductions** [comment]
> Use SetLeapMode (https://github.com/leapmotion/LeapUnreal#set-leap-mode) to change optimization and orientation to desktop tracking in e.g. begin play

This function doesn't seem to change anything, added directly to animblueprints or even world blueprints, hands are still reversed.

**Comment by getnamo** [comment]
I found a bug in this function which would stop it from setting the desktop optimization. This has now been fixed in https://github.com/leapmotion/LeapUnreal/commit/9fdc714c01b3eb7de2e3887a533f507758ab092e

**Comment by BaazarProductions** [comment]
Hi Jan,

Thanks for the update however Set Desktop Mode still has no functionality. Hands are always reversed whether set to Desktop Mode or VR Mode. (I have update the plugin, modules, and LeapMotion installer.) 

One blueprint for desktop mode seems to work in the modules however opening the blueprint crashes the editor in 4.22. 

As a reminder the goal was the be able to use mocap hand tracking on a custom rig, not in VR Mode.

**Comment by getnamo** [comment]
Which blueprint causes the crash?

Fixing the irregular bone anim crash is still on the docked, but I've been unable to find time just yet. I recommend manual rigging in meantime (see direct rigging examples)
