### ISSUE TITLE
Get Images or Frames

### ISSUE THREAD

**Issue by lumbbumba** [leapmotion/LeapUnreal#41]
Hi,

I am trying to get an image or a video capture like in the Leap Motion Visualizer build in Unity for Unreal. 
Is there any way to get the image in C++?

**Comment by getnamo** [comment]
Use SetLeapPolicy to enable raw image streaming (https://github.com/leapmotion/LeapUnreal#set-leap-policy), then subscribe to the OnImageEvent on your leap component https://github.com/leapmotion/LeapUnreal/blob/master/Source/LeapMotion/Public/LeapComponent.h#L74

**Comment by lumbbumba** [comment]
> Use SetLeapPolicy to enable raw image streaming (https://github.com/leapmotion/LeapUnreal#set-leap-policy), then subscribe to the OnImageEvent on your leap component https://github.com/leapmotion/LeapUnreal/blob/master/Source/LeapMotion/Public/LeapComponent.h#L74

Ty really much. It works. Now I need to convert the 2DTexture type to a format where I can use open cv with.
