### ISSUE TITLE
Project Northstar support?

### ISSUE THREAD

**Issue by lumbbumba** [leapmotion/LeapUnreal#42]
Hi, 

is there anyway to get Project Northstar support for #UE4 with this plugin?
It would be very nice to use Unreal Engine with it.

Ty

**Comment by BryanChrisBrown** [comment]
Hi @lumbbumba my team and I just finished a steamvr driver for project Northstar so now you can run it with any engine you choose. Here's a link! 
https://github.com/druidsbane/openvr-northstar
