### ISSUE TITLE
How should I use this plugin in andorid?

### ISSUE THREAD

**Issue by linqingwudiv1** [leapmotion/LeapUnreal#44]
I find a demon andorid apk and the it can correctly identify leap motion device on my android device(Snapdragon820/830).
I don't know why when I use this plugins to build a apk on ue4,I can't identify to leap motion device.
Is it not support Android? or .so file is not matching the device version ?
I spent a lot of time on it.
I hope can who help or reply me. thank.😭

**Comment by clkruse** [comment]
Unfortunately, Leap Motion does not support android with our modules/plugins or service/daemon at this time. If you are in possession of a Leap Motion .apk, it is an early engineering prototype from 2016 that is unsupported.
