### ISSUE TITLE
Leap Orientation Always Flipped

### ISSUE THREAD

**Issue by z3099644** [leapmotion/LeapUnreal#45]
Hi @getnamo, I realize that this is probably beyond the scope of the plug in - but I am finding that every time I restart the computer I need to go to the leap motion control panel and click 'reverse orientation'. This is even with "auto orient tracking" unchecked. Do you know why it's not remembering my preferred orientation and is there a way I can work around this without having to change it every time?

Thanks!

**Comment by getnamo** [comment]
Is this for desktop use or vr? Sounds like some setting isn't triggering right.

**Comment by z3099644** [comment]
It's for VR use. =)

**Comment by xoel** [comment]
Hi! Did you find any solution?
We are working with leap motion on a museum, and every day, some leap motion, changes the orientation on his own, so we need to access remotely to change it again.

**Comment by z3099644** [comment]
Sorry @xoel , we haven't found a solution yet. =(

Please let us know if you find anything.

**Comment by xoel** [comment]
OK. We are trying to find a way to set the orientation by code when we initialize the app.

**Comment by xoel** [comment]
BTW we are working on unity
