### ISSUE TITLE
LeapUnreal 3.3.5 / Unreal 4.22 -> No hands tracking

### ISSUE THREAD

**Issue by naseradd** [leapmotion/LeapUnreal#51]
Hi everyone,

I don't manage to resolve an issue since few days. I had a 4.18 UE project which worked well with the leapmotion plugin. After an update of this project to **4.22**, I upgrade the leapplugin from **3.3.1 to 3.3.5 but I do not have any tracking of the hands on the project.**

**The tracking work well with the visualizer of the leap motion control panel** but not at all with Unreal. I tried the readme explanation to implement the leapmotion quickly but there is no tracking. **I can't detect any event in the leap component**.

Did someone has the same issue as me , or a fix for it ? Thanks in advance !

**Comment by getnamo** [comment]
3.3.5 might be too new, try https://github.com/leapmotion/LeapUnreal/releases/tag/v3.3.4 or the 4.22 variant of https://github.com/leapmotion/LeapUnreal/releases/tag/v3.3.1. Also try https://github.com/leapmotion/LeapUnrealModules which have working examples

**Comment by naseradd** [comment]
3.3.1 and the other version didn't work either. I already tried it and it doesn't change anything.

**Comment by getnamo** [comment]
Do you have the latest runtime installed https://warehouse.leapmotion.com/apps/4621/download?

**Comment by getnamo** [comment]
Just tested https://github.com/leapmotion/LeapUnrealModules/releases/tag/v0.3.7 (LeapUnrealModules-v0.3.7-UE4.22.7z
) with https://github.com/leapmotion/LeapUnreal/releases/tag/v3.3.1 plugin release (LeapMotion-v3.3.1-UE4.22.7z) dragged into the project folder and use PIE VR Preview. Everything seems to work.

**Comment by naseradd** [comment]
I reinstall the same package (https://warehouse.leapmotion.com/apps/4621/download?) That I did before but it seem to work now .. weird anyway thank you and sorry for the trouble.
