### ISSUE TITLE
Position is NaN

### ISSUE THREAD

**Issue by matteogiuliano** [leapmotion/LeapUnreal#52]
Hello, I'm developing an Unreal application using UE 4.22.3 and Leap Motion plugin 3.3.1.
I noticed that starting from the second run in the editor the position of the palm of my hand is [X, Nan, Nan]. Even closing and reopening the project doesn't seem to help.
Restarting the Leap Service seems to make things work for one run only, then the problem reappears.
The same happened with the version of the plugin packed with Unreal Engine.
This is how I'm logging the hand position:
![image](https://user-images.githubusercontent.com/22144381/59919327-717a8100-9427-11e9-82f2-cd8993d9d63e.png)
Thank you for your help.

**Comment by getnamo** [comment]
The usual way to fetch data is to run a for loop over hands array and access inside the loop, but the above logic seems sound. I'll try to replicate the bug.

**Comment by matteogiuliano** [comment]
Thank you,
I've done some more experiments and it seems to be related to the "set leap mode" node.
![image](https://user-images.githubusercontent.com/22144381/59962807-971c8e80-94ea-11e9-95ca-45fcbae7e74f.png)
To replicate:
- Restart the leap service
- Use the "set leap mode" node in the begin play
- Log the palm position
- Everything should work
- Stop the "Play in editor"
- Play in editor again
- Position of the palm should be [X, Nan, Nan]

To confirm:
- Restart the leap service
- Use the "set leap mode" node in the begin play
- Log the palm position
- Everything should work
- Stop the "Play in editor"
- **Remove the "set leap mode" node**
- Play in editor again
- Everything should work

Thank you for your help.
