### ISSUE TITLE
"Plugin 'LeapMotion' failed to load because module 'LeapMotionEditor' could not be found. (custom engine bp project)

### ISSUE THREAD

**Issue by catherineyqiu** [leapmotion/LeapUnreal#54]
Hi, I downloaded LeapMotion-v2.17.1-UE4.19.7z because i'm using an older project file on UE4 version 4.19.2 but when I drag the Plugins folder into my root folder and try to run the project, it says "Plugin 'LeapMotion' failed to load because module 'LeapMotionEditor' could not be found. Please ensure the plugin is properly installed, otherwise consider disabling the plugin for this project" and I can't open the project.  When I delete that folder, I can open the project again.

**Comment by getnamo** [comment]
Did you drag the plugins folder into your project root or engine root folder? (the correct way to use the github release is to drag them into your *project* root folder) Can you confirm the plugins folder contains the folder **LeapMotion/Binaries**?

**Comment by catherineyqiu** [comment]
I've been dragging the plugins folder into my project root folder. 
![image](https://user-images.githubusercontent.com/46725246/63545792-10c9fc00-c4dd-11e9-9ff0-b644d08bed80.png)

And this is what's inside Plugins/LeapMotion/Binaries
![image](https://user-images.githubusercontent.com/46725246/63545866-3820c900-c4dd-11e9-98d4-95281c2074d8.png)

**Comment by getnamo** [comment]
That seems correct, are you using a custom 4.19 engine version or the canonical one, used from the launcher?

**Comment by catherineyqiu** [comment]
It was a custom 4.19 engine, but I'm trying the canonical one now!

**Comment by catherineyqiu** [comment]
Actually, is there any way I can make this plugin work for the custom 4.19 engine? When I try to convert, it messes up my actual project.

**Comment by getnamo** [comment]
There is, but you just need to convert your blueprint only project to a mixed project (add an empty c++ class, see e.g. https://allarsblog.com/2015/11/04/converting-bp-project-to-cpp/ for older detailed guide) and then recompile the project which will recompile the plugin along with it. You can also place the plugin in the engine plugins folder and recompile your custom engine to include it.

You can also very likely take a newer version of the plugin and recompile it for an older engine build with no or maybe only minor fixes.
