### ISSUE TITLE
No clear explanation for connecting LeapMotion with UE4 VR Oculus with Blueprint. its first time to me to use this device, but how can I connect it? I do not have any idea, I hoped there would be some reference in documentation section :( 

### ISSUE THREAD

**Issue by Timurpc** [leapmotion/LeapUnreal#55]

**Comment by getnamo** [comment]
See https://github.com/leapmotion/LeapUnreal#how-to-use-it---convenience-rigged-pawn and https://www.youtube.com/watch?v=z4HIqr-5kWQ&feature=youtu.be

**Comment by Timurpc** [comment]
Hello Mr.
Thanks for responding! I could not use grab and drop functions, could you
help me please?
[image: Leap_Grab_Error.png]

**Comment by Timurpc** [comment]
[image: Problem_Grab_Drop.png]

**Comment by getnamo** [comment]
Your images are not being shown correctly, but assuming you want to do pickup/drop there is a simple example found here: https://github.com/leapmotion/leapunrealmodules#vr-pickup-and-drop with a video of it in action here: https://www.youtube.com/watch?v=dkZD1JuSSnM&feature=youtu.be

**Comment by Timurpc** [comment]
Thanks, I've already checked this. But it's not working in UE 4.22 I
checked Blueprints and there is an error node, I sent you a screenshot of
that error node. That error found in "LeapPhysicsLowPolyHand" Blueprint. I
circled the error node.
[image: Problem_Grab_Drop.png]

Even I cannot touch other objects, I checked collision and physics. But
when I grab my hand it's printing string but not touching...
Can you send me a blueprint with a controller pawn? Even it is okay if you
want to sell, I can buy because it is really important to me now.

Thanks for responding.

Sincerely Timur
