### ISSUE TITLE
Package Project fails with 'LeapMannequinLiveLink_C' Error 

### ISSUE THREAD

**Issue by robotogre** [leapmotion/LeapUnreal#56]
When I add the Leap Motion plugin into my UE4 project, AND even with the official "LeapUnrealModules" UE4 project, both fail to package to Windows 64-bit, with the following error:

`PackagingResults: Error: UStructProperty::Serialize Loading: Property 'StructProperty /Game/Modules/Rigging/LiveLink/LeapMannequinLiveLink.LeapMannequinLiveLink_C:AnimGraphNode_LiveLinkPose_043E904945C258D1A611D5968D234F1A'. Unknown structure.`

UE4: 4.23
Orion: 4 (Latest downloaded)

What is wrong?

**Comment by JimSimons-UH** [comment]
Closed as now fixed
