### ISSUE TITLE
Is latest version v3.5.0 compatible with UE 4.23.1?

### ISSUE THREAD

**Issue by z3099644** [leapmotion/LeapUnreal#58]
In the change log you state that it's compatible with 4.23.0 but is it also compatible with 4.23.1?

The plug in runs okay in editor, and when I package in development mode it is fine too. But when I package in shipping mode, the game crashes on start up? If I then package the game without the plug in, it does not crash.

I have converted the project to a C++ project so it's not that.

**Comment by z3099644** [comment]
Is anyone else experiencing this? I am seeing this on a blank new project so hopefully it's easy to replicate it?

**Comment by CPlusPlusLBC** [comment]
I have the same issure,is there any solution?

**Comment by z3099644** [comment]
Not that I know of yet...

**Comment by getnamo** [comment]
@z3099644 I'm not currently directly involved with the plugin, you need to reach out to https://forums.leapmotion.com/ to get a status on an update

**Comment by z3099644** [comment]
Aw sorry to hear that you're no longer directly involved.

Thanks for the forum link. I'm having trouble posting on that forum at the moment (HTTP ERROR 422) but I'll keep trying.

If you have any other leads we can chase please let us know.
