### ISSUE TITLE
coordinate axis problem on custom rigging

### ISSUE THREAD

**Issue by ShinSaeki** [leapmotion/LeapUnreal#59]
Hi, I followed your guide to setup the direct rigging and it doesn't work...
![キャプチャ](https://user-images.githubusercontent.com/24206056/70123706-8fc2f900-16b6-11ea-9068-29784549b64c.JPG)

I think the coordinate axis seems to be shifted by 90 degrees on the Z axis Between Leapmotion and Unreal... Is there any solutions to convert the value before passing it to the skeleton?

**Comment by JimSimons-UH** [comment]
Closing this as from a much older version of the plugin, please try with the latest version and re-open if it's still an issue
