### ISSUE TITLE
can i use the 3.5.0 on UN4.24 ?

### ISSUE THREAD

**Issue by m9o7h** [leapmotion/LeapUnreal#60]

**Comment by HMH0726** [comment]
No I can't..........

**Comment by z3099644** [comment]
https://forums.leapmotion.com/t/requesting-plugin-compatible-with-ue-4-24/8510

**Comment by benjyvc** [comment]
Yes, please.

**Comment by MaxPalmer-UH** [comment]
Just pushed a branch that should work for HMD based hand tracking on 4.25. Needs more review before it can be merged to main, but available to try out and  play with.
