### ISSUE TITLE
Hand sensitivity support for Unreal Blueprints.

### ISSUE THREAD

**Issue by eelaukka** [leapmotion/LeapUnreal#63]
I have been looking for a way to make the hand movement in the application faster/slower than real-life movement for my application but it does not seem to be supported. This support could be an easy and useful new feature.

Also any suggestions for me to modify the plugins so I could achieve this?

**Comment by JimSimons-UH** [comment]
@eelaukka thanks for the enquiry, this is worth checking on the Unreal forums, see the sequencer for how to record and playback actors in Unreal.  https://forums.unrealengine.com/
