### ISSUE TITLE
Can I Set VR mode without VR headset? 

### ISSUE THREAD

**Issue by vvlay9090** [leapmotion/LeapUnreal#66]
Hello all,
Does anyone try to set VR mode without VR headset?
I've got an issue in which I try to set Leap Mode to VR mode, UE4 crushed every time. I put "Set Leap Mode" after "Event Begin", I don't know how to fix it. 
Can anybody help me please?

**Comment by JimSimons-UH** [comment]
@vvlay9090 thanks for reporting the problem, please try with the latest version and let us know if there's still an issue.
