### ISSUE TITLE
No .7z file for version 3.6.0 

### ISSUE THREAD

**Issue by TreyWojo** [leapmotion/LeapUnreal#69]
New Leap Motion user, first time trying to install the plugin. Tried using the source code since there is no .7z version. Tried on both 4.25.4 and 4.26.0 from the available files, but it says that the following modules are missing:

LeapMotion
LeapMotionEditor
BodyState

Any attempt to rebuilt fails, would love some help with this. Thanks for taking a look at it.

**Comment by omidghajar** [comment]
I am having the same problem 4.25.4, is there any solutions?

**Comment by Abelhibert** [comment]
same problem here, hope a solution come in short term

**Comment by MateSteinforth** [comment]
The compiled binaries are (assumedly wrongly?) contained in the source zip file. Just put the content into ...\[myproject]\Plugins\LeapMotion\[downloaded content] and it should recompile once on start.

**Comment by omidghajar** [comment]
> The compiled binaries are (assumedly wrongly?) contained in the source zip file. Just put the content into ...[myproject]\Plugins\LeapMotion[downloaded content] and it should recompile once on start.

These errors occur upon compiling them, unfortunately.
![Upload
![Error 2](https://user-images.githubusercontent.com/73571955/103457433-4bcb7900-4d3a-11eb-83ae-259f71071d0f.jpg)
ing Error 1.jpg…]()

**Comment by omidghajar** [comment]
Guys, I have good news, I was able to rebuild and make the plugin work, here is the video I have recorded yesterday, I will share the workflow and steps with you all how to rebuild and make the plugin work for UE4.25 this week 👍 💯 
sorry for the background music as I was listening to Sopity while I was recording my screen 👯 

https://user-images.githubusercontent.com/73571955/104557025-80fd9280-567b-11eb-99de-87bf8ebcc1da.mp4

**Comment by Abelhibert** [comment]
amazing! thank you

**Comment by omidghajar** [comment]
Hey sorry guys for my late reply and posting how to rebuild and compile the Plugin, I was busy and caught up with some projects,

Straight to the point, I will be explaining step by step with pictures for ease of understanding, **How to Rebuild Leap Motion Plugin in Unreal Engine 4.25 or 4.26** successfully.

1- First you need to go to the link and download **Microsoft Visual Studio 2019** [,](https://visualstudio.microsoft.com/downloads/) then make sure you download the community version as it is free, upon installation, you will prompt to tick what kind of installation components you want to install, and follow the picture which is idle for Unreal Engine.
![Step (1)](https://user-images.githubusercontent.com/73571955/106023770-13814580-6102-11eb-98fe-f5c43a81a4db.jpg)

2- Second, after installation, download the latest Leap Motion Plugin, in your project folder, create a folder calls "**Plugins**" and then extract the LeapUnreal-3.6.0.zip file into the "**Plugins**" folder.
![Step (2)](https://user-images.githubusercontent.com/73571955/106023998-4aeff200-6102-11eb-8e05-f421aa07eae6.jpg)

3- After extractions, click on the project file to open, then you will prompt with the rebuilding the plugin, click on **Yes** to begin the rebuilding process.
![Step (3)](https://user-images.githubusercontent.com/73571955/106024151-71ae2880-6102-11eb-9c50-ce6b40c9ee3b.jpg)

4- You need to wait for the rebuild process, you do need to do anything, just sit back, you can click on **Show Log** to see the rebuilding process if you like to, it might take a while depends on your system.
![Step (4)](https://user-images.githubusercontent.com/73571955/106024322-a0c49a00-6102-11eb-8e44-9c18ffbbead9.jpg)

5- Once the rebuild process is done, the project automatically will be opened as the picture below
![Step (5)](https://user-images.githubusercontent.com/73571955/106024437-c0f45900-6102-11eb-9bdc-52948b6561e0.jpg)

6- **BINGO!** Unreal Engine has rebuilt the plugin successfully, as you tick show plugin content, you can find Leap Motion Content folder in under you plugin content.
![Step (6)](https://user-images.githubusercontent.com/73571955/106024776-13357a00-6103-11eb-9da6-dc22a418d22f.jpg)

7- I suggest to close Unreal and connect your leap motion and then reopen your project and you are ready to configure and use your beautiful leap motion controller, you can check the "**How to use it - Convenience Rigged Pawn**" following the link at [](https://github.com/leapmotion/LeapUnreal)

PS:  If you have a VR setup alongside your Leap Motion Controller, you can start with **Option 1.** VR Mode- Example Pawn and test your Leap Motion Controller and VR set in VR Mode, if you do not have VR set, you can still use **Option 2.** Desktop Mode - Example Actor to begin to use your Leap Motion Controller without using VR mode in Normal Play Mode or Simulation Mode.

You can check out the test video of Realtime Leap Motion Controller in Unreal Engine.

https://user-images.githubusercontent.com/73571955/106026153-6a881a00-6104-11eb-93c2-cb69bd655da8.mp4



Hope this could help you to kickstart your amazing journey with Leap Motion Controller and Unreal Engine.

Cheers 👍 

Regards.
Omid.

**Comment by omidghajar** [comment]
> amazing! thank you

Hey buddy, you're welcome and check the solution above 👍 good luck
