### ISSUE TITLE
Pinch input is also detected as grab input.

### ISSUE THREAD

**Issue by SebastienTussiau** [leapmotion/LeapUnreal#73]
When using the LPinch input event, when I do a grab with the hands it is considered as a pinch..

**Comment by Ultraleap-Dan** [comment]
We have fixed this issue and this is currently going through QA testing. 

This fix is currently available via the pull request [here](https://github.com/leapmotion/LeapUnreal/pull/76).

**Comment by Ultraleap-Dan** [comment]
This fix is now available in the main [release](https://github.com/leapmotion/LeapUnreal/releases/tag/v3.7.11).

**Comment by SebastienTussiau** [comment]
Great! Thank you guys
