### ISSUE TITLE
Plugin not working when building in shipping configuration in UE4.26.

### ISSUE THREAD

**Issue by SebastienTussiau** [leapmotion/LeapUnreal#77]
I get a "fatal error" message when building the .exe of the game in the Shipping configuration in UE4.26 Does anyone have this problem?

**Comment by JimSimons-UH** [comment]
Hi Sebastien,

Can you post the log/errors from the output log window in UE(Window->Developer tools->Output log)?

I've tested this here with the plugin inside a standard VR template project and it builds with the latest code.

**Comment by SebastienTussiau** [comment]
This error got fixed when I removed the"-master" name of the folder of the plugin. And I also modified in the .uplugin file the deprecated module type "Developer" and turned it into "DeveloperTool". https://docs.unrealengine.com/en-US/API/Runtime/Projects/EHostType__Type/index.html

**Comment by JimSimons-UH** [comment]
Thanks for the additional info.

**Comment by SebastienTussiau** [comment]
De nada!
