### ISSUE TITLE
test_leap_motion could not be compiled. Try rebuilding from source manually.

### ISSUE THREAD

**Issue by Lorenz365** [leapmotion/LeapUnreal#78]
Hello,

i need to use Leap motion plugin for unreal. i've downloaded the latest version of the plugin, of visual studio and .net framework SDK. The hardware Leap Motion Controller for Desktop/Laptops is correctly installed, the plugin is in the correct location but i can't rebuilt it correctly in order to activate it in my project. I'm using UE 4.26.1, I've also tried with UE 4.25.4 but i can't fix the problem. that's the last part of my log:

LogPluginManager: Mounting plugin LeapMotion
LogInit: Warning: Incompatible or missing module: LeapMotion
LogInit: Warning: Incompatible or missing module: LeapMotionEditor
LogInit: Warning: Incompatible or missing module: BodyState
Running C:/Program Files/Epic Games/UE_4.25/Engine/Binaries/DotNET/UnrealBuildTool.exe Development Win64 -Project="D:/test_leap_motion_02/test_leap_motion_02.uproject" -TargetType=Editor -Progress -NoEngineChanges -NoHotReloadFromIDE
@progress push 5%
@progress pop
Target is up to date
Total execution time: 0,68 seconds
LogInit: Warning: Still incompatible or missing module: LeapMotion
LogInit: Warning: Still incompatible or missing module: LeapMotionEditor
LogInit: Warning: Still incompatible or missing module: BodyState
LogCore: Engine exit requested (reason: EngineExit() was called)
LogExit: Preparing to exit.
LogModuleManager: Shutting down and abandoning module DesktopPlatform (48)
LogModuleManager: Shutting down and abandoning module PythonScriptPluginPreload (46)
LogModuleManager: Shutting down and abandoning module PlatformCryptoOpenSSL (44)
LogModuleManager: Shutting down and abandoning module PlatformCryptoTypes (42)
LogModuleManager: Shutting down and abandoning module PlatformCrypto (40)
LogModuleManager: Shutting down and abandoning module AnimationModifiers (38)
LogModuleManager: Shutting down and abandoning module PropertyEditor (37)
LogModuleManager: Shutting down and abandoning module AudioEditor (34)
LogModuleManager: Shutting down and abandoning module TextureCompressor (32)
LogModuleManager: Shutting down and abandoning module RenderCore (30)
LogModuleManager: Shutting down and abandoning module Landscape (28)
LogModuleManager: Shutting down and abandoning module SlateRHIRenderer (26)
LogModuleManager: Shutting down and abandoning module OpenGLDrv (24)
LogModuleManager: Shutting down and abandoning module D3D11RHI (22)
LogModuleManager: Shutting down and abandoning module AnimGraphRuntime (20)
LogModuleManager: Shutting down and abandoning module Renderer (18)
LogModuleManager: Shutting down and abandoning module Engine (16)
LogModuleManager: Shutting down and abandoning module CoreUObject (14)
LogModuleManager: Shutting down and abandoning module NetworkFile (12)
LogModuleManager: Shutting down and abandoning module CookedIterativeFile (10)
LogModuleManager: Shutting down and abandoning module StreamingFile (8)
LogModuleManager: Shutting down and abandoning module SandboxFile (6)
LogModuleManager: Shutting down and abandoning module PakFile (4)
LogModuleManager: Shutting down and abandoning module RSA (3)
LogExit: Exiting.
Log file closed, 03/23/21 15:01:41

thank you

**Comment by JimSimons-UH** [comment]
Hi Lorenz,

Can you add the earlier part of your log, another 20 lines or so should show the build error before this.

**Comment by Lorenz365** [comment]
*hello Jim,*

*that's my log: *


Log file open, 03/26/21 09:55:22
LogInit: LLM is enabled
LogInit: LLM CsvWriter: off TraceWriter: off
LogInit: Display: Running engine for game: test_leap_motion_02
LogPlatformFile: Not using cached read wrapper
LogTaskGraph: Started task graph with 5 named threads and 83 total threads
with 3 sets of task threads.
LogStats: Stats thread started at 0.368427
LogD3D11RHI: Loaded GFSDK_Aftermath_Lib.x64.dll
LogICUInternationalization: ICU TimeZone Detection - Raw Offset: +1:00,
Platform Override: ''
LogPluginManager: Mounting plugin MeshPainting
LogPluginManager: Mounting plugin XGEController
LogPluginManager: Mounting plugin Paper2D
LogPluginManager: Mounting plugin EnvironmentQueryEditor
LogPluginManager: Mounting plugin AISupport
LogPluginManager: Mounting plugin LightPropagationVolume
LogPluginManager: Mounting plugin CameraShakePreviewer
LogPluginManager: Mounting plugin AxFImporter
LogPluginManager: Mounting plugin DatasmithCADImporter
LogPluginManager: Mounting plugin DatasmithContent
LogPluginManager: Mounting plugin DatasmithGLTFImporter
LogPluginManager: Mounting plugin DataprepEditor
LogPluginManager: Mounting plugin DatasmithIFCImporter
LogPluginManager: Mounting plugin StaticMeshEditorExtension
LogPluginManager: Mounting plugin VariantManager
LogPluginManager: Mounting plugin DatasmithImporter
LogPluginManager: Mounting plugin VariantManagerContent
LogPluginManager: Mounting plugin AssetManagerEditor
LogPluginManager: Mounting plugin EditorScriptingUtilities
LogPluginManager: Mounting plugin CurveEditorTools
LogPluginManager: Mounting plugin CryptoKeys
LogPluginManager: Mounting plugin DataValidation
LogPluginManager: Mounting plugin FacialAnimation
LogPluginManager: Mounting plugin GeometryMode
LogPluginManager: Mounting plugin MeshEditor
LogPluginManager: Mounting plugin GameplayTagsEditor
LogPluginManager: Mounting plugin MacGraphicsSwitching
LogPluginManager: Mounting plugin GLTFImporter
LogPluginManager: Mounting plugin MobileLauncherProfileWizard
LogPluginManager: Mounting plugin MaterialAnalyzer
LogPluginManager: Mounting plugin SpeedTreeImporter
LogPluginManager: Mounting plugin PluginBrowser
LogPluginManager: Mounting plugin AnimationSharing
LogPluginManager: Mounting plugin CLionSourceCodeAccess
LogPluginManager: Mounting plugin CodeLiteSourceCodeAccess
LogPluginManager: Mounting plugin PropertyAccessNode
LogPluginManager: Mounting plugin NullSourceCodeAccess
LogPluginManager: Mounting plugin KDevelopSourceCodeAccess
LogPluginManager: Mounting plugin GitSourceControl
LogPluginManager: Mounting plugin SubversionSourceControl
LogPluginManager: Mounting plugin PerforceSourceControl
LogPluginManager: Mounting plugin PluginUtils
LogPluginManager: Mounting plugin VisualStudioSourceCodeAccess
LogPluginManager: Mounting plugin RiderSourceCodeAccess
LogPluginManager: Mounting plugin UObjectPlugin
LogPluginManager: Mounting plugin PlasticSourceControl
LogPluginManager: Mounting plugin VisualStudioCodeSourceCodeAccess
LogPluginManager: Mounting plugin XCodeSourceCodeAccess
LogPluginManager: Mounting plugin AlembicImporter
LogPluginManager: Mounting plugin AutomationUtils
LogPluginManager: Mounting plugin ChaosClothEditor
LogPluginManager: Mounting plugin BackChannel
LogPluginManager: Mounting plugin ChaosEditor
LogPluginManager: Mounting plugin ChaosNiagara
LogPluginManager: Mounting plugin ChaosCloth
LogPluginManager: Mounting plugin BlastPlugin
LogPluginManager: Mounting plugin CharacterAI
LogPluginManager: Mounting plugin ChaosSolverPlugin
LogPluginManager: Mounting plugin GeometryCache
LogPluginManager: Mounting plugin GeometryCollectionPlugin
LogPluginManager: Mounting plugin GeometryProcessing
LogPluginManager: Mounting plugin MotoSynth
LogPluginManager: Mounting plugin PlanarCut
LogPluginManager: Mounting plugin PlatformCrypto
LogPluginManager: Mounting plugin PythonScriptPlugin
LogPluginManager: Mounting plugin ProxyLODPlugin
LogPluginManager: Mounting plugin SkeletalReduction
LogPluginManager: Mounting plugin Niagara
LogPluginManager: Mounting plugin AndroidMedia
LogPluginManager: Mounting plugin AvfMedia
LogPluginManager: Mounting plugin ImgMedia
LogPluginManager: Mounting plugin MediaCompositing
LogPluginManager: Mounting plugin MediaPlayerEditor
LogPluginManager: Mounting plugin WebMMedia
LogPluginManager: Mounting plugin WmfMedia
LogPluginManager: Mounting plugin LuminPlatformFeatures
LogPluginManager: Mounting plugin MagicLeap
LogPluginManager: Mounting plugin MagicLeapLightEstimation
LogPluginManager: Mounting plugin MagicLeapMedia
LogPluginManager: Mounting plugin MagicLeapPassableWorld
LogPluginManager: Mounting plugin MLSDK
LogPluginManager: Mounting plugin TcpMessaging
LogPluginManager: Mounting plugin UdpMessaging
LogPluginManager: Mounting plugin OnlineSubsystem
LogPluginManager: Mounting plugin OnlineSubsystemNull
LogPluginManager: Mounting plugin OnlineSubsystemUtils
LogPluginManager: Mounting plugin ActorSequence
LogPluginManager: Mounting plugin LevelSequenceEditor
LogPluginManager: Mounting plugin LauncherChunkInstaller
LogPluginManager: Mounting plugin TemplateSequence
LogPluginManager: Mounting plugin MatineeToLevelSequence
LogPluginManager: Mounting plugin ActorLayerUtilities
LogPluginManager: Mounting plugin AndroidDeviceProfileSelector
LogPluginManager: Mounting plugin AndroidMoviePlayer
LogPluginManager: Mounting plugin AndroidPermission
LogPluginManager: Mounting plugin AppleMoviePlayer
LogPluginManager: Mounting plugin AppleImageUtils
LogPluginManager: Mounting plugin ArchVisCharacter
LogPluginManager: Mounting plugin AssetTags
LogPluginManager: Mounting plugin AudioCapture
LogPluginManager: Mounting plugin ChunkDownloader
LogPluginManager: Mounting plugin ExampleDeviceProfileSelector
LogPluginManager: Mounting plugin AudioSynesthesia
LogPluginManager: Mounting plugin CustomMeshComponent
LogPluginManager: Mounting plugin EditableMesh
LogPluginManager: Mounting plugin CableComponent
LogPluginManager: Mounting plugin GoogleCloudMessaging
LogPluginManager: Mounting plugin GooglePAD
LogPluginManager: Mounting plugin HDRIBackdrop
LogPluginManager: Mounting plugin ScreenshotTools
LogPluginManager: Mounting plugin LinuxDeviceProfileSelector
LogPluginManager: Mounting plugin IOSDeviceProfileSelector
LogPluginManager: Mounting plugin LocationServicesBPLibrary
LogPluginManager: Mounting plugin MobilePatchingUtils
LogPluginManager: Mounting plugin PhysXVehicles
LogPluginManager: Mounting plugin PostSplashScreen
LogPluginManager: Mounting plugin ProceduralMeshComponent
LogPluginManager: Mounting plugin SignificanceManager
LogPluginManager: Mounting plugin PropertyAccessEditor
LogPluginManager: Mounting plugin RuntimePhysXCooking
LogPluginManager: Mounting plugin SoundFields
LogPluginManager: Mounting plugin Synthesis
LogPluginManager: Mounting plugin SunPosition
LogPluginManager: Mounting plugin WebMMoviePlayer
LogPluginManager: Mounting plugin WindowsMoviePlayer
LogPluginManager: Mounting plugin ContentBrowserAssetDataSource
LogPluginManager: Mounting plugin ContentBrowserClassDataSource
LogPluginManager: Mounting plugin ContentBrowserFileDataSource
LogPluginManager: Mounting plugin OnlineSubsystemGooglePlay
LogPluginManager: Mounting plugin OnlineSubsystemIOS
LogPluginManager: Mounting plugin OculusVR
LogPluginManager: Mounting plugin SteamVR
LogPluginManager: Mounting plugin LeapMotion
LogXGEController: Cleaning working directory:
C:/Users/Fabrizio/AppData/Local/Temp/UnrealXGEWorkingDir/
LogXGEController: Cannot use XGE Controller as Incredibuild is not
installed on this machine.
LogInit: Warning: Incompatible or missing module: LeapMotion
LogInit: Warning: Incompatible or missing module: LeapMotionEditor
LogInit: Warning: Incompatible or missing module: BodyState
Running C:/Program Files/Epic
Games/UE_4.26/Engine/Binaries/DotNET/UnrealBuildTool.exe Development Win64
-Project="D:/test_leap_motion_02/test_leap_motion_02.uproject"
-TargetType=Editor -Progress -NoEngineChanges -NoHotReloadFromIDE
Creating makefile for UE4Editor (.uproject file is newer)
Project plugin detected, using dll at
D:\test_leap_motion_02\Plugins\LeapUnreal\Binaries\Win64\LeapC.dll
LeapPlugin: Copied from
D:\test_leap_motion_02\Plugins\LeapUnreal\Binaries\Win64\LeapC.dll, to
D:\test_leap_motion_02\Binaries\Win64\LeapC.dll
Project plugin detected, using dll at
D:\test_leap_motion_02\Plugins\LeapUnreal\Binaries\Win64\LeapC.dll
@progress push 5%
Parsing headers for UE4Editor
  Running UnrealHeaderTool
"D:\test_leap_motion_02\test_leap_motion_02.uproject"
"D:\test_leap_motion_02\Intermediate\Build\Win64\UE4Editor\Development\UE4Editor.uhtmanifest"
-LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended
-WarningsAsErrors
-abslog="C:\Users\Fabrizio\AppData\Local\UnrealBuildTool\Log_UHT.txt"
-installed
Reflection code generated for UE4Editor in 36,5018552 seconds
@progress pop
Building UE4Editor...
Using Visual Studio 2019 14.28.29913 toolchain (C:\Program Files
(x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910) and
Windows 10.0.19041.0 SDK (C:\Program Files (x86)\Windows Kits\10).
Building 18 actions with 32 processes...
  @progress 'Compiling C++ source code...' 0%
  @progress 'Compiling C++ source code...' 6%
  [1/18] Default.rc2
  @progress 'Compiling C++ source code...' 11%
  [2/18] Default.rc2
  @progress 'Compiling C++ source code...' 17%
  [3/18] Default.rc2
  @progress 'Compiling C++ source code...' 22%
  [4/18] SharedPCH.UnrealEd.ShadowErrors.cpp
  @progress 'Compiling C++ source code...' 28%
  [5/18] SharedPCH.Engine.ShadowErrors.cpp
  @progress 'Compiling C++ source code...' 33%
  [6/18] Module.LeapMotion.cpp

D:/test_leap_motion_02/Plugins/LeapUnreal/Source/LeapMotion/Private/LeapImage.cpp(83):
error C2027: utilizzo di tipo non definito 'FTexture2DResource'
  C:\Program Files\Epic
Games\UE_4.26\Engine\Source\Runtime\Engine\Classes\Engine/Texture2D.h(15):
note: vedere la dichiarazione di 'FTexture2DResource'

D:/test_leap_motion_02/Plugins/LeapUnreal/Source/LeapMotion/Private/LeapImage.cpp(87):
error C2027: utilizzo di tipo non definito 'FTexture2DResource'
  C:\Program Files\Epic
Games\UE_4.26\Engine\Source\Runtime\Engine\Classes\Engine/Texture2D.h(15):
note: vedere la dichiarazione di 'FTexture2DResource'
  @progress 'Compiling C++ source code...' 39%
  [7/18] Module.LeapMotion.gen.cpp
  @progress 'Compiling C++ source code...' 44%
  [8/18] Module.BodyState.gen.cpp
  @progress 'Compiling C++ source code...' 50%
  [9/18] Module.LeapMotionEditor.cpp
  @progress 'Compiling C++ source code...' 56%
  [10/18] Module.LeapMotionEditor.gen.cpp
  @progress 'Compiling C++ source code...' 61%
  [11/18] UE4Editor-LeapMotionEditor.lib
     Creazione della libreria
D:\test_leap_motion_02\Plugins\LeapUnreal\Intermediate\Build\Win64\UE4Editor\Development\LeapMotionEditor\UE4Editor-LeapMotionEditor.lib
e dell'oggetto
D:\test_leap_motion_02\Plugins\LeapUnreal\Intermediate\Build\Win64\UE4Editor\Development\LeapMotionEditor\UE4Editor-LeapMotionEditor.exp
  @progress 'Compiling C++ source code...' 67%
  [12/18] Module.BodyState.cpp
  @progress 'Compiling C++ source code...' 72%
  [13/18] UE4Editor-BodyState.lib
     Creazione della libreria
D:\test_leap_motion_02\Plugins\LeapUnreal\Intermediate\Build\Win64\UE4Editor\Development\BodyState\UE4Editor-BodyState.lib
e dell'oggetto
D:\test_leap_motion_02\Plugins\LeapUnreal\Intermediate\Build\Win64\UE4Editor\Development\BodyState\UE4Editor-BodyState.exp
  @progress 'Compiling C++ source code...' 78%
  [14/18] UE4Editor-BodyState.dll
     Creazione della libreria
D:\test_leap_motion_02\Plugins\LeapUnreal\Intermediate\Build\Win64\UE4Editor\Development\BodyState\UE4Editor-BodyState.suppressed.lib
e dell'oggetto
D:\test_leap_motion_02\Plugins\LeapUnreal\Intermediate\Build\Win64\UE4Editor\Development\BodyState\UE4Editor-BodyState.suppressed.exp
LogInit: Warning: Still incompatible or missing module: LeapMotion
LogInit: Warning: Still incompatible or missing module: LeapMotionEditor
LogInit: Warning: Still incompatible or missing module: BodyState
LogCore: Engine exit requested (reason: EngineExit() was called)
LogExit: Preparing to exit.
LogModuleManager: Shutting down and abandoning module DesktopPlatform (50)
LogModuleManager: Shutting down and abandoning module
PythonScriptPluginPreload (48)
LogModuleManager: Shutting down and abandoning module PlatformCryptoOpenSSL
(46)
LogModuleManager: Shutting down and abandoning module PlatformCryptoTypes
(44)
LogModuleManager: Shutting down and abandoning module PlatformCrypto (42)
LogModuleManager: Shutting down and abandoning module XGEController (40)
LogXGEController: Cleaning working directory:
C:/Users/Fabrizio/AppData/Local/Temp/UnrealXGEWorkingDir/
LogModuleManager: Shutting down and abandoning module AnimationModifiers
(38)
LogModuleManager: Shutting down and abandoning module AudioEditor (36)
LogModuleManager: Shutting down and abandoning module PropertyEditor (35)
LogModuleManager: Shutting down and abandoning module TextureCompressor (32)
LogModuleManager: Shutting down and abandoning module RenderCore (30)
LogModuleManager: Shutting down and abandoning module Landscape (28)
LogModuleManager: Shutting down and abandoning module SlateRHIRenderer (26)
LogModuleManager: Shutting down and abandoning module OpenGLDrv (24)
LogModuleManager: Shutting down and abandoning module D3D11RHI (22)
LogModuleManager: Shutting down and abandoning module AnimGraphRuntime (20)
LogModuleManager: Shutting down and abandoning module Renderer (18)
LogModuleManager: Shutting down and abandoning module Engine (16)
LogModuleManager: Shutting down and abandoning module CoreUObject (14)
LogModuleManager: Shutting down and abandoning module NetworkFile (12)
LogModuleManager: Shutting down and abandoning module CookedIterativeFile
(10)
LogModuleManager: Shutting down and abandoning module StreamingFile (8)
LogModuleManager: Shutting down and abandoning module SandboxFile (6)
LogModuleManager: Shutting down and abandoning module PakFile (4)
LogModuleManager: Shutting down and abandoning module RSA (3)
LogExit: Exiting.
Log file closed, 03/26/21 09:57:43


*thank you*
*FL*


Il giorno mar 23 mar 2021 alle ore 15:29 JimSimons-UH <
***@***.***> ha scritto:

**Comment by JimSimons-UH** [comment]
Hi, 
This is fixed in the current release of the plugin, pull the latest code or download the zip from this repo and it'll build.
