### ISSUE TITLE
Project will not open once plugin is put in the project folder.

### ISSUE THREAD

**Issue by mattyough25** [leapmotion/LeapUnreal#79]
After I create a "Plugins" folder in a new project and place the Leap plugin in it, I am unable to open the project. I get two separate errors that are as follows.

1)
"The following modules are missing or built with a different engine version:

LeapMotion
LeapMotionEditor
BodyState

Would you like to rebuild them now?"

So I click yes, and then get this.

2)
"[ProjectName] could not be compiled. Try rebuilding from source manually"

I have the latest version of Unreal Engine (4.26), and I have even tried downloading past versions of Unreal Engine (ex. 4.25) but I get the same error.

**Comment by JimSimons-UH** [comment]
Hi @mattyough25, Can you post your log file at /Saved/Logs/[YourProjectName].log.

When Unreal has this error, you can build in Visual Studio. To do this:

- Right click on your .uproject files
- Choose Generate Visual Studio Files
- Open the .sln file and build it
- You'll then be able to open the .uproject as normal.

**Comment by Lorenz365** [comment]
Hello Jim, 

latest release seems not working with UE 4.26 although I build it via Visual Studio. I found a workaround switching to 4.25, downloading LeapUnrealModules project and building the plug in via unreal while opening the editor. In that way I can copy the working plugin folder in the main root of another project, but always using UE 4.25.

**Comment by JimSimons-UH** [comment]
Hi Lorenz, 

How are you getting the release from here - via git clone?

**Comment by Lorenz365** [comment]
hello Jim,

      i downloaded the latest release via .zip but unfortunately i have the
same problem Maybe i should try via git clone, but if the .zip file is the
correct one I don't understand where the issue is.

Il giorno lun 29 mar 2021 alle ore 10:23 JimSimons-UH <
***@***.***> ha scritto:

**Comment by JimSimons-UH** [comment]
Hi Lorenz,
Can you post your log from Saved\Logs in the project folder? 

Another thing to check:
- If downloaded from zip, rename the plugin to LeapUnreal (from LeapUnreal-Master)
- Download the zip from private/incognito mode to check it's not cached somewhere.

**Comment by Lorenz365** [comment]
Hi Jim,

         finally seems it worked! I renamed the folder and i downloaded in
incognito mode the zip file. Let me asking something more: unfortunately
i'm not really a developer nevertheless i'm tring to build a project in
unreal using leap motion controller. I need to simply inspect an object
(rotate,tilt, bla bla) and explode it via animation (visually specking).
It's very hard to find some specific documentation that can help me. (i've
already seen the online documentation, but i think  i need something more
step by step for my case) Do you have any suggestions about it? Anyway,
thank you so far for your time and your help in letting the plug in working
for the 4.26 version. Really appreciated.

Best

FL

Il giorno mar 30 mar 2021 alle ore 13:31 JimSimons-UH <
***@***.***> ha scritto:

**Comment by JimSimons-UH** [comment]
Great to hear you got it working, In terms of your specific project, it's really about learning Unreal using the documentation out there, both official and by the community. The  Leapmodules project is a good starting point for building hand interaction.
