### ISSUE TITLE
Package not including LeapC.dll in 4.26

### ISSUE THREAD

**Issue by gwburger** [leapmotion/LeapUnreal#83]
I am able to use the plugin without issue in the editor, and I have not had any errors packaging the plugin after applying the fixes noted in #77. The packaged executable will run without crashing, but I do not have any LeapMotion functionality. I notice that the logs are reporting error 126, and LeapC.dll is nowhere to be found in the packaged game files. I have followed all of the steps outlined in the Packaging directions in the readme.

I apologize if there is some obvious solution that I am not seeing, I have had no luck browsing through the documentation on using third-party libraries in UE4. I have had some success using third-party libraries in previous versions of UE4. so I think something may have changed in the latest update.

**Comment by JimSimons-UH** [comment]
Hi, Thanks for reporting the issue.

Please don't modify the .uplugin file (leave the module type as Developer not Developer tool as posted in #77.  This breaks the packaged build.
