### ISSUE TITLE
Assertion failed: !Pose crash every time on editor

### ISSUE THREAD

**Issue by SinanAkkoyun** [leapmotion/LeapUnreal#84]
Assertion failed: !Pose[BoneIndex].ContainsNaN() [File:C:\Program Files\Epic Games\UE_4.25\Engine\Source\Runtime\Engine\Public\BonePose.h] [Line: 564]

I think it only happens due to the editor preview of the LEAP hands. Can one disable the live editor feed?

**Comment by Ultraleap-Dan** [comment]
Please can you confirm which version of the Ultraleap Unreal Plugin and which specific version of Unreal Engine you are using?

**Comment by SinanAkkoyun** [comment]
Yes, I am using LeapUnreal-3.6.0 and UE4.25.4

I hope soon the plugin supports 4.26.2

**Comment by JimSimons-UH** [comment]
Hi Sinan, 

If you get the latest code from here, it does now support both 4.25.4 and 4.26.2. This may also resolve the assert you're seeing.

**Comment by JimSimons-UH** [comment]
the lastest version on the master supports all version 4.25 - > 4.26.2. It's just that there isn't a prebuilt/binary version for 4.26 yet.

**Comment by SinanAkkoyun** [comment]
That is odd, because when I recompile the latest code with 4.26 it fails everytime because of some 2D Texture stuff missing...

**Comment by JimSimons-UH** [comment]
you need to get the latest code from this repository. So go to the green code button and either clone or download the zip. This supports 4.26.
![image](https://user-images.githubusercontent.com/76523080/119646013-91d2c780-be16-11eb-9dce-40b56653aa8a.png)

**Comment by Ultraleap-Dan** [comment]
In addition to the above there is now a binary release available [here](https://github.com/leapmotion/LeapUnreal/releases/tag/v3.7.11).

Please can you let us know if you are still experiencing any issues?
