### ISSUE TITLE
Cannot load the plugin in UR 4.26.1.

### ISSUE THREAD

**Issue by th-ink** [leapmotion/LeapUnreal#86]
After downloading v3.7.1. release and copying it in the Plugins folder, opening the project results in error:  
`Plugin 'LeapMotion' failed to load because module 'LeapMotion' could not be loaded. There may be an operating system error or the module may not be properly set up.` Lookinga at the generated logs, I can see this:
`0]LogModuleManager: Warning: ModuleManager: Unable to load module 'C:/Users/peter/Documents/Unreal Projects/LeapMotionProject/Plugins/LeapMotion/Binaries/Win64/UE4Editor-LeapMotion.dll' because the file couldn't be loaded by the OS.`
The Leap Motion Visualizer does work, if that changes anything.

**Comment by JimSimons-UH** [comment]
Hi @th-ink, thanks for reporting this, 
This is now resolved - please re-download the zip at https://github.com/leapmotion/LeapUnreal/releases/tag/v3.7.11

**Comment by th-ink** [comment]
Can confirm that v3.7.11 version has resolved this issue. Thank you!

**Comment by JimSimons-UH** [comment]
great, thanks for the update.
