### ISSUE TITLE
UNABLE TO CONNECT HANDS TO MY 3D MODEL

### ISSUE THREAD

**Issue by designstazz** [leapmotion/LeapUnreal#87]
I'm trying to move my 3d character hands using leap motion. I tried everything and still not make it. Is there anyone that know how to do it?

**Comment by Ultraleap-Dan** [comment]
Please go here to look at our [Leap Unreal Modules](https://github.com/leapmotion/LeapUnrealModules/) which will help with these. I have also included two examples below of rigged hands that you can use:

https://github.com/leapmotion/LeapUnreal/tree/master/Content/DirectRigging/LowPoly

https://github.com/leapmotion/LeapUnrealModules/tree/master/Content/Modules/Rigging
