### ISSUE TITLE
Vibrating UI when attached to hand

### ISSUE THREAD

**Issue by SebastienTussiau** [leapmotion/LeapUnreal#88]
How to reduce the amount of vibrations a UI gets if attached to the left hand for example?

**Comment by JimSimons-UH** [comment]
Hi Sebastien, 

Check out the pickup and drop examples in the LeapUnrealModules project: https://github.com/leapmotion/LeapUnrealModules/tree/master/Content/Modules/PickupAndDrop

These use physics handles to grab items. Physics handles can be configured to different levels of stiffness giving a smoothing effect.

Alternatively, if you don't want to use the physics engine, interpolate the attached Actor or Component's position on tick to smooth it's location towards the attach location (i.e. don't attach directly, update the position instead to follow the desired attach location).
