### ISSUE TITLE
Leapmotion crush

### ISSUE THREAD

**Issue by cortek** [leapmotion/LeapUnreal#89]
Suddenly there was a problem.
All the assets I have worked with still work.

But if I want to make a reparent BodyStateAnimInstance and add a Modify Mapped Bones node.

I get such a crash.
And this is in all projects

---------

LoginId:e96eee4f4b28dcd7727a2f873dc9577d
EpicAccountId:233249e1054b444281c6682f489eaa5e

Assertion failed: (Index >= 0) & (Index < ArrayNum) [File:C:\UnrealPrebuilt\UE_4.26\Engine\Source\Runtime\Core\Public\Containers/Array.h] [Line: 674] Array index out of bounds: -1 from an array of size 16

UE4Editor_Core
UE4Editor_Core
UE4Editor_BodyState
UE4Editor_BodyState
UE4Editor_BodyState
UE4Editor_BodyState
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_Engine
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_UnrealEd
UE4Editor_Kismet
UE4Editor_Kismet
UE4Editor_Kismet
UE4Editor_UnrealEd
UE4Editor_Kismet
UE4Editor_AnimationBlueprintEditor
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_Slate
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore
UE4Editor_ApplicationCore
user32
user32
UE4Editor_ApplicationCore
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll

**Comment by Ultraleap-Dan** [comment]
This issue is now fixed in the master branch.
