### ISSUE TITLE
HANDS  DON'T MOVE PROPERTLY HELP PLSSSSS

### ISSUE THREAD

**Issue by designstazz** [leapmotion/LeapUnreal#90]
Hello everyone! 

I just downloaded the LeapMotionModules, and started seeing things. But I have a problem when my hands get tracked. LOOK THE PICTURE
![image](https://user-images.githubusercontent.com/86025567/124396447-e452ae00-dd09-11eb-9612-61e65a0c565b.png)
 
this happens to meee the arm moves upon the center and the hands seem to be mirrored back! HELP

**Comment by Ultraleap-Dan** [comment]
Please can you check the diagnostic visualiser in the Leap Motion Control Panel to check that the hand tracking looks to be correct here as well as making sure that the hardware orientation set and tracking mode active in Unreal?

If you post some screenshots of these here I will be happy to check them for you.

**Comment by designstazz** [comment]
First of all thanks for answering me!

The Diagnostic visualizer looks good to me....
![image](https://user-images.githubusercontent.com/86025567/124512945-ed12b500-ddd9-11eb-8727-ce47e1d68964.png)

I'm using the Leap Motion as desktop mode, with other apps is well detected but with Unreal makes like a strange mirror (like in the image you have seen). I'm now to that so... what do you refer or where I can find if the tracking mode, the orientation and more at Unreal? I was looking at the BP but couldn't find anything!

One more time, thanks for helping me with that, my objective is make my own 3d model move the  hands and track my movements!

**Comment by Ultraleap-Dan** [comment]
Thank you for this information. Please can you check that you are selecting the correct blueprint for the correct mode. The mode used is typically mentioned in the name of the blueprint and this then sets the mode as part of its code. For example if you use LeapDesktopActor this will set the mode to desktop mode.

If you open the blueprint you will see something grabbing LeapOptions and then setting the mode to the correct one on the options data. You should not change the blueprint to a different mode. The correct practice for this is to use the correct blueprint for the mode that you with to use. Our hand tracking can support multiple clients bu the mode is global to all clients., so changing this in the visualiser will change it for everything used the hand tracking data. 

Please take care not to open more than one client or the tracking will be running in whatever mode the most recent client chose.

Is desktop mode the desired one for your use case? If so, I recommend having a look at LeapDesktopActor to help to correct the hand tracking orientation which should help to resolve this issue.

**Comment by ConnorBurg** [comment]
Hi,
I believe that I ran into a similar situation in desktop mode, here's how I solved it: I went into the LeapDesktopActor BP editor > Viewport and rotate the orientation of the hands (Child Actor) so that the axes in the editor matched my hand movement. You can use trial and error by rotating one of the axes, checking if that is getting you closer to the desired output, and keep doing iterations of those steps until the BP matches your hand orientation. Once you save/compile LeapDesktopActor in the BP editor, you should have it working in the correct orientation in your level. 

Once you put that into your level, your hands should be tracking in the right orientation.
