### ISSUE TITLE
Rotation twitches at certain point

### ISSUE THREAD

**Issue by frizzlminizzl** [leapmotion/LeapUnreal#91]
Hey everyone,
I'm trying to pin a simple cube to my Index-Fingertip and the cube should follow the rotation of that finger. The translation is no problem, I just use break LeapPalmData --> break LeapDigitData --> break LeapBoneData and set the WorldLocation of that cube to the BoneData "NextJoint" but whenever im using the rotation, the cube at some point (I think it might be 0/180/260°) makes a jump into a new (random?) orientation. For the rotation of the cube I'm using the BoneData's "Rotation" and set the cube's rotation ( I tried World and Relative) to that BoneData rotation. 
Does anybody know why this ist or even better, how to fix it?
I'm having a hard time debugging...I tried breakpoints after x-repeats and print Rotators to screen and recorded that, but the twitch is so fast, that I can't really detect the reason for that weird behaviour.
So does anybody know how to handle this?
Thanks in advance!

**Comment by Ultraleap-Dan** [comment]
If you try changing the interpolation settings, in the API this is called `setLeapOptions`, or turn interpolation on if this is currently off.
