### ISSUE TITLE
Unreal Log Warning: Script Msg: Attempted to access index 1 from array 'Hands' of length 1

### ISSUE THREAD

**Issue by SebastienTussiau** [leapmotion/LeapUnreal#92]
Hello, I am getting this yellow warning in the logs of Unreal, could someone explain me what it is? And how to fix that?

LogScript: Warning: Script Msg: Attempted to access index 1 from array 'Hands' of length 1 in '/Script/LeapMotion.LeapFrameData'!

**Comment by JimSimons-UH** [comment]
Hi Sebastien,

This means in blueprint somewhere, there is something accessing the Hands array whilst the hands array doesn't have both hands tracked. It's always best to use a for loop in blueprint over the hands rather than hardwiring the indices.
