### ISSUE TITLE
how can i reduce latency when tracking 2 hands with the character mesh from the LeapMotionModule

### ISSUE THREAD

**Issue by PezzyDD** [leapmotion/LeapUnreal#95]
Hello everyone

I’m trying to use the LeapMotion with Unreal and Visualizer (Vr mode), but experiencing high level of latency when displaying two hands. It seems to work fine with only one hand. I’ve only added an custom offset and blend to the tracked animation.

https://user-images.githubusercontent.com/44117607/126679198-5bab1518-1284-4cd8-b0ca-60e7394d53e4.mp4

I am suspecting that the Visualizer is causing the latency. So I tried without the Visualizer, but it broke everything as shown in the video below:

https://user-images.githubusercontent.com/44117607/126679285-ed4c2bcc-2c9d-4ed9-9c95-34a60e0a7742.mp4

I also tried to use the **set leap mode** function to change mode, but then UE4 just crashes or the IK breaks as shown in the videos below:

https://user-images.githubusercontent.com/44117607/126679395-e5252937-1e58-4bfe-9929-361ebe14e95d.mp4

https://user-images.githubusercontent.com/44117607/126681695-c99e68f7-e0f6-4708-978c-c8b08c826357.mp4

Any suggestions on how to reduce latency/fix these issues?
Is the Visualizer necessary or can I just use the  “set leap mode” function?

**Comment by JimSimons-UH** [comment]
Hi @PezzyDD, 

Thanks for posting the videos. 

As an experiment, can you put a delay node between the BeginPlay and SetLeapMode nodes in the level blueprint with a delay of  0.2 seconds, and see if this still causes a NaN assert.

**Comment by PezzyDD** [comment]
plugin version is LeapUnreal-3.6.0 in unreal engine 4.26

**Comment by JimSimons-UH** [comment]
It's worth trying the latest plugin release https://github.com/leapmotion/LeapUnreal/releases/tag/v3.7.11 too as there's many big fixes applied since 3.6.0

**Comment by PezzyDD** [comment]
Sorry for the delayed response.

so how can i find the multi thread option? Where is it? I tried to create a new project, updated to the new plugin, plugged the delay node to the level’s blueprint, but I’m still facing the same problem.

**Comment by JimSimons-UH** [comment]
@PezzyDD the multithreaded option is on the details of the animinstance blueprints, so in the screen shot above, it's the Echo_Skeleton_AnimBlueprint that's opened. Then select the settings icon (cog icon) on the toolbar and then you can access the settings in the details tab as shown in the screen shot.

**Comment by PezzyDD** [comment]
Alright, I see it. So I’m using UE4 and its still crashing when I play. i’m not sure if its because of my pc/hardware? A solution I found for the latency issue when displaying two hands is to select the “Low Resource Mode” in the Leap motion control panel. Both hands are now moving smoothly, but I still need to use the visualizer to switch the modes. Do you have any suggestions on how I can switch the modes using UE4 instead?

**Comment by JimSimons-UH** [comment]
Unfortunately, there isn't a way of switching Low Resource mode apart from via the Leap Motion Control Panel. 
Can you send a .zip of your test project? This'll help us to reproduce the crash you're seeing.

**Comment by PezzyDD** [comment]
7z : [https://drive.google.com/file/d/1p8nMl6IT9nftGJRpgecMnsrpuzQb1Vzl/view?usp=sharing](url)
my custom animblueprint contain in \testNewPlugin\Content\new_blueprint

**Comment by JimSimons-UH** [comment]
Thanks for the example, I can't repro the issue you're seeing - a NAN (not a number) assert. 

I've added some test code to block any NAN values coming from the tracking device. To try it out, clone the leap plugin from https://github.com/JimSimons-UH/LeapUnreal/tree/NAN_filtering. This will eliminate any bad tracking data getting through on your system if this is the cause of the issue.

**Comment by Ultraleap-Dan** [comment]
This fix is now included in the master branch.
